classdef WorldTest < matlab.unittest.TestCase
    %WORLDTEST Tests physical-world composition and stable UE identity.

    methods (Test)
        function testComposesVehiclesAndRsusInStableUeOrder(testCase)
            scenario = testCase.createScenario( ...
                ["V2", "V1"], [20, 10], ["V2", "V1"], [20, 10]);
            rsuPositions = testCase.createRsuPositions( ...
                ["RSU2", "RSU1"], [200, 100]);

            world = v2xsim.World(scenario, rsuPositions);

            testCase.verifyEqual(world.VehicleIds, ["V2"; "V1"]);
            testCase.verifyEqual(world.RsuIds, ["RSU2"; "RSU1"]);
            testCase.verifyEqual( ...
                world.UeIds, ["V2"; "V1"; "RSU2"; "RSU1"]);
            testCase.verifyEqual( ...
                string(world.VehiclePositions.Properties.RowNames), ...
                ["V2"; "V1"]);
            testCase.verifyEqual( ...
                string(world.UePositions.Properties.RowNames), ...
                ["V2"; "V1"; "RSU2"; "RSU1"]);
            testCase.verifyEqual(world.UePositions.X, [20; 10; 200; 100]);
        end

        function testAcceptsNoRsus(testCase)
            scenario = testCase.createScenario( ...
                ["V1", "V2"], [1, 2], ["V1", "V2"], [1, 2]);

            world = v2xsim.World(scenario);

            testCase.verifyEmpty(world.RsuIds);
            testCase.verifyEqual(world.UeIds, world.VehicleIds);
            testCase.verifyEqual( ...
                world.UePositions, world.VehiclePositions);
            testCase.verifyClass( ...
                world.ObstacleGeometry, ...
                "v2xsim.world.EmptyObstacleGeometry");
            testCase.verifyFalse( ...
                world.ObstacleGeometry.hasObstacles());
        end

        function testStepMovesOnlyVehiclesAndKeepsRsusFixed(testCase)
            scenario = testCase.createScenario( ...
                ["V1", "V2"], [1, 2], ["V1", "V2"], [11, 12]);
            rsuPositions = testCase.createRsuPositions( ...
                ["RSU1", "RSU2"], [100, 200]);
            world = v2xsim.World(scenario, rsuPositions);
            originalWorld = world;

            [steppedWorld, transitions] = world.step(0.5);

            testCase.verifyEqual(steppedWorld.VehiclePositions.X, [11; 12]);
            testCase.verifyEqual( ...
                steppedWorld.RsuPositions, originalWorld.RsuPositions);
            testCase.verifyEqual( ...
                steppedWorld.UePositions.X, [11; 12; 100; 200]);
            testCase.verifyEqual( ...
                originalWorld.VehiclePositions.X, [1; 2], ...
                "World must preserve value-class semantics.");
            testCase.verifyEqual( ...
                string(transitions.Properties.RowNames), ["V1"; "V2"]);
        end

        function testStepPreservesWorldOrderWhenScenarioReordersRows(testCase)
            scenario = testCase.createScenario( ...
                ["V1", "V2"], [1, 2], ["V2", "V1"], [20, 10]);
            world = v2xsim.World(scenario);

            world = world.step(1);

            testCase.verifyEqual(world.VehicleIds, ["V1"; "V2"]);
            testCase.verifyEqual( ...
                string(world.VehiclePositions.Properties.RowNames), ...
                ["V1"; "V2"]);
            testCase.verifyEqual(world.VehiclePositions.X, [10; 20]);
        end

        function testAcceptsArbitraryVehicleAndRsuNames(testCase)
            scenario = testCase.createScenario( ...
                ["Car-A", "delivery van"], [1, 2], ...
                ["Car-A", "delivery van"], [1, 2]);
            rsuPositions = testCase.createRsuPositions( ...
                ["Tower-West", "V1"], [100, 200]);

            world = v2xsim.World(scenario,rsuPositions);

            testCase.verifyEqual( ...
                world.VehicleIds,["Car-A";"delivery van"]);
            testCase.verifyEqual( ...
                world.RsuIds,["Tower-West";"V1"]);
            testCase.verifyEqual( ...
                world.UeIds, ...
                ["Car-A";"delivery van";"Tower-West";"V1"]);
        end

        function testRejectsDuplicateNameAcrossVehicleAndRsu(testCase)
            scenario = testCase.createScenario( ...
                "shared-name", 1, "shared-name", 1);
            rsuPositions = testCase.createRsuPositions( ...
                "shared-name",100);

            testCase.verifyError( ...
                @() v2xsim.World(scenario, rsuPositions), ...
                "v2xsim:world:DuplicateUeIds");
        end

        function testRejectsUnnamedRsus(testCase)
            scenario = testCase.createScenario( ...
                "V1", 1, "V1", 1);
            rsuPositions = table( ...
                100, 200, VariableNames=["X", "Y"]);

            testCase.verifyError( ...
                @() v2xsim.World(scenario, rsuPositions), ...
                "v2xsim:world:MissingRsuIds");
        end

        function testRejectsInvalidRsuPositionSchema(testCase)
            scenario = testCase.createScenario( ...
                "V1", 1, "V1", 1);
            rsuPositions = table( ...
                100, 200, zeros(1, 1), ...
                VariableNames=["X", "Y", "Z"], ...
                RowNames="RSU1");

            testCase.verifyError( ...
                @() v2xsim.World(scenario, rsuPositions), ...
                "v2xsim:world:InvalidRsuPositions");
        end
    end

    methods (Access = private)
        function scenario = createScenario( ...
                testCase, initialIds, initialX, nextIds, nextX)
            initialKinematics = testCase.createKinematics( ...
                initialIds, initialX);
            nextKinematics = testCase.createKinematics(nextIds, nextX);
            transitions = testCase.createUnchangedTransitions(nextIds);

            scenario = v2xsimtest.vehicle.scenario.fixture.ScenarioStub( ...
                initialKinematics, nextKinematics, transitions);
        end

        function kinematics = createKinematics(~, ids, x)
            ids = string(ids(:));
            x = double(x(:));
            vehicleCount = numel(ids);
            y = 100 + x;
            unknown = NaN(vehicleCount, 1);

            kinematics = table( ...
                x, y, unknown, unknown, unknown, unknown, ...
                VariableNames=["X", "Y", "vX", "vY", "aX", "aY"], ...
                RowNames=cellstr(ids));
        end

        function transitions = createUnchangedTransitions(~, ids)
            import v2xsim.vehicle.scenario.VehicleLifecycleTransition

            ids = string(ids(:));
            transition = repmat( ...
                VehicleLifecycleTransition.Unchanged, numel(ids), 1);
            transitions = table( ...
                transition, ...
                VariableNames="Transition", ...
                RowNames=cellstr(ids));
        end

        function rsuPositions = createRsuPositions(~, ids, x)
            ids = string(ids(:));
            x = double(x(:));
            y = 1000 + x;
            rsuPositions = table( ...
                x, y, ...
                VariableNames=["X", "Y"], ...
                RowNames=cellstr(ids));
        end
    end
end
