classdef ConstantSpeed < ...
        v2xsim.vehicle.scenario.highway.MobilityModel
    %CONSTANTSPEED Fixed-speed lane motion with periodic wraparound.

    methods
        function obj = ConstantSpeed(speed)
            arguments (Input)
                speed (1, 1) double ...
                    {mustBeReal, mustBeFinite, mustBeNonnegative}
            end

            obj = obj@v2xsim.vehicle.scenario.highway.MobilityModel( ...
                speed, 0, false, RandStream.getGlobalStream());
        end

        function [obj, vehicleKinematics, vehicleLaneStates] = ...
                initializeKinematics(obj, ~, vehiclePlacement)
            speed = repmat( ...
                obj.MeanVehicleSpeed, height(vehiclePlacement), 1);
            vehicleKinematics = ...
                v2xsim.vehicle.scenario.highway.MobilityModel.createKinematics( ...
                    vehiclePlacement, speed);
            vehicleLaneStates = ...
                v2xsim.vehicle.scenario.highway.MobilityModel.extractLaneStates( ...
                    vehiclePlacement);
        end

        function [obj, vehicleKinematics, vehicleLaneStates] = ...
                resolvePositionConstraints( ...
                obj, geometry, previousVehicleKinematics, ...
                vehicleKinematics, previousVehicleLaneStates, ~)
            vehicleKinematics.X = mod( ...
                vehicleKinematics.X, geometry.RoadLength);
            vehicleKinematics.Y = previousVehicleKinematics.Y;
            vehicleKinematics.vY(:) = 0;
            vehicleLaneStates = ...
                v2xsim.vehicle.scenario.highway.MobilityModel.updateMainlineProgress( ...
                    geometry, vehicleKinematics, ...
                    previousVehicleLaneStates);
        end
    end
end
