classdef ExitRamp < ...
        v2xsim.vehicle.scenario.highway.mobility.RerollingSpeed
    %EXITRAMP Route-aware mobility for a symmetric highway lane drop.
    %   Outer-lane vehicles choose the ramp with ExitProbability at each
    %   fork. Otherwise, they merge into the adjacent lane. Both branches
    %   recycle to the upstream outer lane, preserving the home-lane
    %   population even though instantaneous lane occupancy can vary.

    properties (SetAccess = immutable)
        ExitProbability (1, 1) double ...
            {mustBeReal, mustBeFinite, mustBeNonnegative} = 0
    end

    properties (SetAccess = private)
        VehicleRoutes table = table()
    end

    methods
        function obj = ExitRamp( ...
                meanVehicleSpeed, vehicleSpeedStandardDeviation, ...
                exitProbability, options)
            arguments (Input)
                meanVehicleSpeed (1, 1) double ...
                    {mustBeReal, mustBeFinite, mustBeNonnegative}
                vehicleSpeedStandardDeviation (1, 1) double ...
                    {mustBeReal, mustBeFinite, mustBeNonnegative}
                exitProbability (1, 1) double ...
                    {mustBeReal, mustBeFinite, mustBeNonnegative}
                options.RerollSpeedOnWrapAround (1, 1) logical = true
                options.RandomStream (1, 1) RandStream = ...
                    RandStream.getGlobalStream()
            end

            if exitProbability > 1
                error( ...
                    "v2xsim:scenario:highway:InvalidExitProbability", ...
                    "ExitProbability must lie between zero and one, " + ...
                    "inclusive.");
            end

            obj = obj@v2xsim.vehicle.scenario.highway.mobility.RerollingSpeed( ...
                meanVehicleSpeed, ...
                vehicleSpeedStandardDeviation, ...
                RerollSpeedOnWrapAround= ...
                    options.RerollSpeedOnWrapAround, ...
                RandomStream=options.RandomStream);
            obj.ExitProbability = exitProbability;
        end

        function [obj, vehicleKinematics] = initializeKinematics( ...
                obj, geometry, vehiclePlacement)
            arguments (Input)
                obj (1, 1)
                geometry (1, 1) ...
                    v2xsim.vehicle.scenario.highway.ExitRampGeometry
                vehiclePlacement table
            end

            requiredVariables = [ ...
                "X", "Y", "HomeLaneIndex", "TravelDirection", "Route"];
            if ~all(ismember( ...
                    requiredVariables, ...
                    string(vehiclePlacement.Properties.VariableNames)))
                error( ...
                    "v2xsim:scenario:highway:MissingExitRampPlacementState", ...
                    "ExitRamp mobility requires placement variables X, " + ...
                    "Y, HomeLaneIndex, TravelDirection, and Route.");
            end

            vehiclePositions = vehiclePlacement(:, ["X", "Y"]);
            [obj, vehicleKinematics] = ...
                initializeKinematics@v2xsim.vehicle.scenario.highway.mobility.RerollingSpeed( ...
                    obj, geometry, vehiclePositions);

            speed = abs(vehicleKinematics.vX);
            obj.VehicleRoutes = table( ...
                vehiclePlacement.HomeLaneIndex, ...
                vehiclePlacement.TravelDirection, ...
                string(vehiclePlacement.Route), ...
                speed, ...
                VariableNames=[ ...
                    "HomeLaneIndex", "TravelDirection", ...
                    "Route", "Speed"], ...
                RowNames=vehiclePlacement.Properties.RowNames);

            vehicleKinematics = obj.applyRouteVelocities( ...
                geometry, vehicleKinematics);
        end

        function [obj, vehicleKinematics] = updateVelocities( ...
                obj, geometry, vehicleKinematics, ~)
            vehicleKinematics = obj.applyRouteVelocities( ...
                geometry, vehicleKinematics);
        end

        function [obj, vehicleKinematics] = resolvePositionConstraints( ...
                obj, geometry, previousVehicleKinematics, ...
                vehicleKinematics, deltaTime)
            arguments (Input)
                obj (1, 1)
                geometry (1, 1) ...
                    v2xsim.vehicle.scenario.highway.ExitRampGeometry
                previousVehicleKinematics table
                vehicleKinematics table
                deltaTime (1, 1) double ...
                    {mustBeReal, mustBeFinite, mustBePositive}
            end

            rowNames = vehicleKinematics.Properties.RowNames;
            previousVehicleKinematics = ...
                previousVehicleKinematics(rowNames, :);
            obj.VehicleRoutes = obj.VehicleRoutes(rowNames, :);
            vehicleKinematics = previousVehicleKinematics;

            for vehicleIndex = 1:height(vehicleKinematics)
                [obj, vehicleKinematics] = obj.advanceVehicle( ...
                    geometry, vehicleKinematics, vehicleIndex, deltaTime);
            end

            vehicleKinematics = obj.applyRouteVelocities( ...
                geometry, vehicleKinematics);
        end

        function validateKinematics(obj, geometry, vehicleKinematics)
            arguments (Input)
                obj (1, 1)
                geometry (1, 1) ...
                    v2xsim.vehicle.scenario.highway.ExitRampGeometry
                vehicleKinematics table
            end

            rowNames = vehicleKinematics.Properties.RowNames;
            if isempty(obj.VehicleRoutes) || ...
                    ~isequal( ...
                        sort(string(obj.VehicleRoutes.Properties.RowNames)), ...
                        sort(string(rowNames)))
                error( ...
                    "v2xsim:scenario:highway:InvalidRouteState", ...
                    "Exit-ramp route state must identify every vehicle.");
            end

            routes = obj.VehicleRoutes(rowNames, :);
            tolerance = 1e-9 .* max( ...
                [1, geometry.RoadLength, geometry.OuterLaneCenter, ...
                max(routes.Speed)]);
            expected = obj;
            expected.VehicleRoutes = routes;
            expectedKinematics = expected.applyRouteVelocities( ...
                geometry, vehicleKinematics);
            wrongVelocity = ...
                abs(vehicleKinematics.vX - expectedKinematics.vX) > ...
                    tolerance | ...
                abs(vehicleKinematics.vY - expectedKinematics.vY) > ...
                    tolerance;
            if any(wrongVelocity)
                error( ...
                    "v2xsim:scenario:highway:InvalidRouteVelocity", ...
                    "Vehicle velocity must be tangent to its active " + ...
                    "mainline, merge, or ramp route.");
            end

            laneCenters = geometry.getAbsoluteLaneCenters();
            for vehicleIndex = 1:height(vehicleKinematics)
                direction = routes.TravelDirection(vehicleIndex);
                homeLane = routes.HomeLaneIndex(vehicleIndex);
                route = routes.Route(vehicleIndex);
                x = vehicleKinematics.X(vehicleIndex);
                y = vehicleKinematics.Y(vehicleIndex);
                horizontalProgress = direction .* (x - geometry.ForkX);

                switch route
                    case "Regular"
                        valid = all(homeLane < geometry.NLanes, "all") && ...
                            all(abs(y - direction .* ...
                            laneCenters(homeLane)) <= tolerance, "all");
                    case "Outer"
                        valid = all( ...
                            homeLane == geometry.NLanes, "all") && ...
                            all(horizontalProgress <= tolerance, "all") && ...
                            all(abs(y - direction .* ...
                                geometry.OuterLaneCenter) <= ...
                                tolerance, "all");
                    case "Ramp"
                        valid = all( ...
                            homeLane == geometry.NLanes, "all") && ...
                            all(horizontalProgress >= -tolerance, "all") && ...
                            all(horizontalProgress <= ...
                                geometry.RoadLength ./ 2 + tolerance, ...
                                "all") && ...
                            all(abs(abs(y) - ...
                                (geometry.OuterLaneCenter + ...
                                horizontalProgress)) <= tolerance, "all");
                    case "Merge"
                        expectedY = geometry.getMergeY( ...
                            direction, horizontalProgress);
                        valid = all( ...
                            homeLane == geometry.NLanes, "all") && ...
                            geometry.MergeDistance > 0 && ...
                            all(horizontalProgress >= -tolerance, "all") && ...
                            all(horizontalProgress <= ...
                                geometry.MergeDistance + tolerance, ...
                                "all") && ...
                            all(abs(y - expectedY) <= tolerance, "all");
                    case "Adjacent"
                        valid = all( ...
                            homeLane == geometry.NLanes, "all") && ...
                            all(horizontalProgress >= ...
                                geometry.MergeDistance - tolerance, ...
                                "all") && ...
                            all(abs(y - direction .* ...
                                geometry.AdjacentLaneCenter) <= ...
                                tolerance, "all");
                    otherwise
                        valid = false;
                end

                if ~valid
                    error( ...
                        "v2xsim:scenario:highway:VehicleOutsideActiveRoute", ...
                        "Vehicle %s is not on its active %s route.", ...
                        rowNames{vehicleIndex}, route);
                end
            end
        end
    end

    methods (Access = private)
        function shouldExit = chooseExit(obj)
            if obj.ExitProbability == 0
                shouldExit = false;
            elseif obj.ExitProbability == 1
                shouldExit = true;
            else
                shouldExit = rand(obj.RandomStream) < obj.ExitProbability;
            end
        end

        function vehicleKinematics = applyRouteVelocities( ...
                obj, geometry, vehicleKinematics)
            routes = obj.VehicleRoutes( ...
                vehicleKinematics.Properties.RowNames, :);
            vehicleKinematics.vX(:) = 0;
            vehicleKinematics.vY(:) = 0;

            straight = routes.Route == "Regular" | ...
                routes.Route == "Outer" | ...
                routes.Route == "Adjacent";
            vehicleKinematics.vX(straight) = ...
                routes.TravelDirection(straight) .* routes.Speed(straight);

            onRamp = routes.Route == "Ramp";
            rampVelocity = routes.TravelDirection(onRamp) .* ...
                routes.Speed(onRamp) ./ sqrt(2);
            vehicleKinematics.vX(onRamp) = rampVelocity;
            vehicleKinematics.vY(onRamp) = rampVelocity;

            onMerge = routes.Route == "Merge";
            vehicleKinematics.vX(onMerge) = ...
                routes.TravelDirection(onMerge) .* routes.Speed(onMerge);
            horizontalProgress = routes.TravelDirection(onMerge) .* ...
                (vehicleKinematics.X(onMerge) - geometry.ForkX);
            lateralSlope = geometry.getMergeLateralSlope( ...
                routes.TravelDirection(onMerge), horizontalProgress);
            vehicleKinematics.vY(onMerge) = ...
                lateralSlope .* routes.Speed(onMerge);
        end

        function [obj, vehicleKinematics] = advanceVehicle( ...
                obj, geometry, vehicleKinematics, vehicleIndex, ...
                remainingTime)
            while remainingTime > 0
                speed = obj.VehicleRoutes.Speed(vehicleIndex);
                if speed == 0
                    break
                end

                direction = ...
                    obj.VehicleRoutes.TravelDirection(vehicleIndex);
                route = obj.VehicleRoutes.Route(vehicleIndex);
                x = vehicleKinematics.X(vehicleIndex);

                switch route
                    case "Regular"
                        distanceToEvent = obj.distanceToBoundary( ...
                            geometry, x, direction);
                        [reachesEvent, travelTime] = obj.getTravelTime( ...
                            distanceToEvent, speed, remainingTime);
                        vehicleKinematics.X(vehicleIndex) = ...
                            x + direction .* speed .* travelTime;
                        remainingTime = remainingTime - travelTime;
                        if reachesEvent
                            homeLane = obj.VehicleRoutes.HomeLaneIndex( ...
                                vehicleIndex);
                            [obj, vehicleKinematics] = obj.recycleVehicle( ...
                                geometry, vehicleKinematics, ...
                                vehicleIndex, homeLane, "Regular");
                        end

                    case "Outer"
                        distanceToEvent = max( ...
                            direction .* (geometry.ForkX - x), 0);
                        [reachesEvent, travelTime] = obj.getTravelTime( ...
                            distanceToEvent, speed, remainingTime);
                        vehicleKinematics.X(vehicleIndex) = ...
                            x + direction .* speed .* travelTime;
                        remainingTime = remainingTime - travelTime;
                        if reachesEvent
                            vehicleKinematics.X(vehicleIndex) = ...
                                geometry.ForkX;
                            if obj.chooseExit()
                                obj.VehicleRoutes.Route(vehicleIndex) = ...
                                    "Ramp";
                            elseif geometry.MergeDistance == 0
                                obj.VehicleRoutes.Route(vehicleIndex) = ...
                                    "Adjacent";
                                vehicleKinematics.Y(vehicleIndex) = ...
                                    direction .* ...
                                    geometry.AdjacentLaneCenter;
                            else
                                obj.VehicleRoutes.Route(vehicleIndex) = ...
                                    "Merge";
                            end
                        end

                    case "Ramp"
                        horizontalProgress = direction .* ...
                            (x - geometry.ForkX);
                        distanceToEvent = sqrt(2) .* max( ...
                            geometry.RoadLength ./ 2 - ...
                            horizontalProgress, 0);
                        [reachesEvent, travelTime] = obj.getTravelTime( ...
                            distanceToEvent, speed, remainingTime);
                        distance = speed .* travelTime;
                        vehicleKinematics.X(vehicleIndex) = ...
                            x + direction .* distance ./ sqrt(2);
                        vehicleKinematics.Y(vehicleIndex) = ...
                            vehicleKinematics.Y(vehicleIndex) + ...
                            direction .* distance ./ sqrt(2);
                        remainingTime = remainingTime - travelTime;
                        if reachesEvent
                            [obj, vehicleKinematics] = obj.recycleVehicle( ...
                                geometry, vehicleKinematics, ...
                                vehicleIndex, geometry.NLanes, "Outer");
                        end

                    case "Merge"
                        horizontalProgress = direction .* ...
                            (x - geometry.ForkX);
                        distanceToEvent = max( ...
                            geometry.MergeDistance - ...
                            horizontalProgress, 0);
                        [reachesEvent, travelTime] = obj.getTravelTime( ...
                            distanceToEvent, speed, remainingTime);
                        newProgress = horizontalProgress + ...
                            speed .* travelTime;
                        vehicleKinematics.X(vehicleIndex) = ...
                            geometry.ForkX + direction .* newProgress;
                        vehicleKinematics.Y(vehicleIndex) = ...
                            geometry.getMergeY(direction, newProgress);
                        remainingTime = remainingTime - travelTime;
                        if reachesEvent
                            obj.VehicleRoutes.Route(vehicleIndex) = ...
                                "Adjacent";
                            vehicleKinematics.Y(vehicleIndex) = ...
                                direction .* ...
                                geometry.AdjacentLaneCenter;
                        end

                    case "Adjacent"
                        distanceToEvent = obj.distanceToBoundary( ...
                            geometry, x, direction);
                        [reachesEvent, travelTime] = obj.getTravelTime( ...
                            distanceToEvent, speed, remainingTime);
                        vehicleKinematics.X(vehicleIndex) = ...
                            x + direction .* speed .* travelTime;
                        remainingTime = remainingTime - travelTime;
                        if reachesEvent
                            [obj, vehicleKinematics] = obj.recycleVehicle( ...
                                geometry, vehicleKinematics, ...
                                vehicleIndex, geometry.NLanes, "Outer");
                        end
                end
            end
        end

        function [obj, vehicleKinematics] = recycleVehicle( ...
                obj, geometry, vehicleKinematics, vehicleIndex, ...
                laneIndex, route)
            direction = obj.VehicleRoutes.TravelDirection(vehicleIndex);
            if direction > 0
                vehicleKinematics.X(vehicleIndex) = 0;
            else
                vehicleKinematics.X(vehicleIndex) = geometry.RoadLength;
            end

            laneCenters = geometry.getAbsoluteLaneCenters();
            vehicleKinematics.Y(vehicleIndex) = ...
                direction .* laneCenters(laneIndex);
            obj.VehicleRoutes.Route(vehicleIndex) = route;

            if obj.RerollSpeedOnWrapAround
                obj.VehicleRoutes.Speed(vehicleIndex) = obj.sampleSpeed(1);
            end
        end
    end

    methods (Static, Access = private)
        function distance = distanceToBoundary(geometry, x, direction)
            if direction > 0
                distance = max(geometry.RoadLength - x, 0);
            else
                distance = max(x, 0);
            end
        end

        function [reachesEvent, travelTime] = getTravelTime( ...
                distanceToEvent, speed, remainingTime)
            timeToEvent = distanceToEvent ./ speed;
            reachesEvent = timeToEvent <= remainingTime;
            travelTime = min(timeToEvent, remainingTime);
        end
    end
end
