classdef RerollingSpeed < ...
        v2xsim.vehicle.scenario.highway.MobilityModel
    %REROLLINGSPEED Normally distributed speed with optional wrap rerolls.

    methods
        function obj = RerollingSpeed( ...
                meanVehicleSpeed, vehicleSpeedStandardDeviation, options)
            arguments (Input)
                meanVehicleSpeed (1, 1) double ...
                    {mustBeReal, mustBeFinite, mustBeNonnegative}
                vehicleSpeedStandardDeviation (1, 1) double ...
                    {mustBeReal, mustBeFinite, mustBeNonnegative}
                options.RerollSpeedOnWrapAround (1, 1) logical = true
                options.RandomStream (1, 1) RandStream = ...
                    RandStream.getGlobalStream()
            end

            obj = obj@v2xsim.vehicle.scenario.highway.MobilityModel( ...
                meanVehicleSpeed, ...
                vehicleSpeedStandardDeviation, ...
                options.RerollSpeedOnWrapAround, ...
                options.RandomStream);
        end

        function [obj, vehicleKinematics] = initializeKinematics( ...
                obj, ~, vehiclePositions)
            speed = ...
                v2xsim.vehicle.scenario.highway.MobilityModel.sampleNonnegativeNormal( ...
                    obj.RandomStream, ...
                    height(vehiclePositions), ...
                    obj.MeanVehicleSpeed, ...
                    obj.VehicleSpeedStandardDeviation);
            vehicleKinematics = ...
                v2xsim.vehicle.scenario.highway.MobilityModel.createKinematics( ...
                    vehiclePositions, speed);
        end

        function [obj, vehicleKinematics] = resolvePositionConstraints( ...
                obj, geometry, previousVehicleKinematics, ...
                vehicleKinematics, deltaTime)
            originalY = previousVehicleKinematics.Y;

            if obj.RerollSpeedOnWrapAround
                travelDirection = sign(originalY);
                [vehicleKinematics.X, vehicleKinematics.vX] = ...
                    obj.advanceAndReroll( ...
                        geometry, ...
                        previousVehicleKinematics.X, ...
                        vehicleKinematics.vX, ...
                        travelDirection, ...
                        deltaTime);
            else
                vehicleKinematics.X = mod( ...
                    vehicleKinematics.X, geometry.RoadLength);
            end

            vehicleKinematics.Y = originalY;
            vehicleKinematics.vY(:) = 0;
        end
    end

    methods (Access = protected)
        function [position, velocity] = advanceAndReroll( ...
                obj, geometry, position, velocity, travelDirection, ...
                deltaTime)
            arguments (Input)
                obj (1, 1)
                geometry (1, 1) ...
                    v2xsim.vehicle.scenario.highway.Geometry
                position (:, 1) double ...
                    {mustBeReal, mustBeFinite}
                velocity (:, 1) double ...
                    {mustBeReal, mustBeFinite}
                travelDirection (:, 1) double ...
                    {mustBeReal, mustBeFinite}
                deltaTime (1, 1) double ...
                    {mustBeReal, mustBeFinite, mustBePositive}
            end

            speed = abs(velocity);

            for vehicleIndex = 1:numel(position)
                remainingTime = deltaTime;

                while remainingTime > 0 && speed(vehicleIndex) > 0
                    if travelDirection(vehicleIndex) > 0
                        distanceToBoundary = ...
                            geometry.RoadLength - position(vehicleIndex);
                    else
                        distanceToBoundary = position(vehicleIndex);
                    end

                    timeToBoundary = ...
                        distanceToBoundary ./ speed(vehicleIndex);

                    if all(remainingTime < timeToBoundary, "all")
                        position(vehicleIndex) = ...
                            position(vehicleIndex) + ...
                            travelDirection(vehicleIndex) .* ...
                            speed(vehicleIndex) .* remainingTime;
                        remainingTime = 0;
                    else
                        remainingTime = remainingTime - timeToBoundary;

                        if travelDirection(vehicleIndex) > 0
                            position(vehicleIndex) = 0;
                        else
                            position(vehicleIndex) = geometry.RoadLength;
                        end

                        speed(vehicleIndex) = obj.sampleSpeed(1);
                    end
                end
            end

            velocity = travelDirection .* speed;
        end

        function speed = sampleSpeed(obj, count)
            speed = ...
                v2xsim.vehicle.scenario.highway.MobilityModel.sampleNonnegativeNormal( ...
                    obj.RandomStream, ...
                    count, ...
                    obj.MeanVehicleSpeed, ...
                    obj.VehicleSpeedStandardDeviation);
        end
    end
end
