classdef (Abstract) ExitRampPositionErrorModule < ...
        v2xsim.positioning.PositionErrorModule
    %EXITRAMPPOSITIONERRORMODULE Base for exit-ramp-only error modules.
    %   This class rejects generic and non-ramp contexts before delegating
    %   to the concrete module implementation.

    methods (Sealed, Access = protected)
        function [obj, outputPositions] = doApply( ...
                obj, inputPositions, context)
            if ~isa( ...
                    context, ...
                    "v2xsim.positioning.ExitRampPositionErrorContext")
                error( ...
                    "v2xsim:positioning:UnsupportedErrorContext", ...
                    "This position error module requires an " + ...
                    "ExitRampPositionErrorContext.");
            end

            [obj, outputPositions] = ...
                obj.doApplyToExitRamp(inputPositions, context);
        end
    end

    methods (Abstract, Access = protected)
        [obj, outputPositions] = doApplyToExitRamp( ...
            obj, inputPositions, context)
    end
end
