classdef FalseMergePositionError < ...
        v2xsim.positioning.FalseRoutePositionErrorModule
    %FALSEMERGEPOSITIONERROR Show exiting vehicles on the mainline merge.
    %   Cursed outer-home-lane vehicles that truly take the exit ramp
    %   appear on the merge connector and then the adjacent mainline lane.

    methods
        function obj = FalseMergePositionError(curseProbability, options)
            arguments (Input)
                curseProbability (1, 1) double ...
                    {mustBeReal, mustBeFinite, mustBeNonnegative}
                options.ResetAfterSeconds (1, 1) double ...
                    {mustBeReal, mustBeNonnegative} = Inf
                options.RandomStream (1, 1) RandStream = ...
                    RandStream.getGlobalStream()
            end

            obj = obj@v2xsim.positioning.FalseRoutePositionErrorModule( ...
                curseProbability, ...
                options.ResetAfterSeconds, ...
                options.RandomStream);
        end
    end

    methods (Access = protected)
        function affectedRoute = isAffectedRoute(~, route)
            affectedRoute = route == "Ramp";
        end

        function falsePositions = calculateFalsePositions( ...
                ~, actualPositions, routeStates, context)
            geometry = context.Geometry;
            direction = routeStates.TravelDirection;
            distancePastFork = direction .* ...
                (actualPositions.X - geometry.ForkX);
            distancePastFork = min(max( ...
                distancePastFork, 0), geometry.RoadLength ./ 2);

            onMergeConnector = false(height(actualPositions), 1);
            if geometry.MergeDistance > 0
                onMergeConnector = ...
                    distancePastFork <= geometry.MergeDistance;
            end
            falsePositions = zeros(height(actualPositions), 2);

            if any(onMergeConnector)
                mergeLaneIds = geometry.getMergeLaneId( ...
                    direction(onMergeConnector));
                mergeProgress = ...
                    distancePastFork(onMergeConnector) ./ ...
                    geometry.MergeDistance;
                falsePositions(onMergeConnector, :) = ...
                    context.LaneNetwork.evaluate( ...
                        mergeLaneIds, mergeProgress);
            end

            onAdjacentLane = ~onMergeConnector;
            if any(onAdjacentLane)
                adjacentLaneIds = geometry.getMainlineLaneId( ...
                    direction(onAdjacentLane), ...
                    (geometry.NLanes - 1) .* ...
                    ones(nnz(onAdjacentLane), 1));
                mainlineProgress = ...
                    actualPositions.X(onAdjacentLane) ./ ...
                    geometry.RoadLength;
                negativeDirection = ...
                    direction(onAdjacentLane) < 0;
                mainlineProgress(negativeDirection) = ...
                    1 - mainlineProgress(negativeDirection);
                falsePositions(onAdjacentLane, :) = ...
                    context.LaneNetwork.evaluate( ...
                        adjacentLaneIds, mainlineProgress);
            end
        end
    end
end
