classdef PositionErrorContext
    %POSITIONERRORCONTEXT Immutable inputs shared by position-error modules.
    %   ActualPositions is the unmodified scenario position snapshot.
    %   SimulationTimeSeconds identifies the current snapshot,
    %   TimeStepSeconds is the position-update interval, and
    %   SimulationDurationSeconds is the configured total duration.

    properties (SetAccess = immutable)
        ActualPositions table ...
            {v2xsim.positioning.validation.mustBe2DPositionTable} = ...
            table( ...
                zeros(0, 1), zeros(0, 1), ...
                VariableNames=["X", "Y"])
        SimulationTimeSeconds (1, 1) double ...
            {mustBeReal, mustBeFinite, mustBeNonnegative} = 0
        TimeStepSeconds (1, 1) double ...
            {mustBeReal, mustBeFinite, mustBePositive} = 1
        SimulationDurationSeconds (1, 1) double ...
            {mustBeReal, mustBeFinite, mustBePositive} = 1
    end

    methods
        function obj = PositionErrorContext( ...
                actualPositions, simulationTimeSeconds, ...
                timeStepSeconds, simulationDurationSeconds)
            arguments (Input)
                actualPositions table ...
                    {v2xsim.positioning.validation.mustBe2DPositionTable}
                simulationTimeSeconds (1, 1) double ...
                    {mustBeReal, mustBeFinite, mustBeNonnegative}
                timeStepSeconds (1, 1) double ...
                    {mustBeReal, mustBeFinite, mustBePositive}
                simulationDurationSeconds (1, 1) double ...
                    {mustBeReal, mustBeFinite, mustBePositive}
            end

            if simulationTimeSeconds > simulationDurationSeconds
                error( ...
                    "v2xsim:positioning:TimeBeyondSimulationDuration", ...
                    "SimulationTimeSeconds cannot exceed " + ...
                    "SimulationDurationSeconds.");
            end

            obj.ActualPositions = actualPositions;
            obj.SimulationTimeSeconds = simulationTimeSeconds;
            obj.TimeStepSeconds = timeStepSeconds;
            obj.SimulationDurationSeconds = ...
                simulationDurationSeconds;
        end
    end
end
