classdef LanedScenarioTest < matlab.unittest.TestCase
    %LANEDSCENARIOTEST Tests lane-network and vehicle-state invariants.

    methods (Test)
        function testExposesNetworkAndAlignedLaneState(testCase)
            [kinematics, laneNetwork, laneStates] = ...
                testCase.createInputs();
            laneStates = flipud(laneStates);

            scenario = ...
                v2xsimtest.vehicle.scenario.fixture.LanedScenarioStub( ...
                    kinematics, laneNetwork, laneStates);

            testCase.verifyEqual(scenario.LaneNetwork, laneNetwork);
            testCase.verifyEqual( ...
                string(scenario.VehicleLaneStates.Properties.RowNames), ...
                string(kinematics.Properties.RowNames));
            testCase.verifyTrue(isa( ...
                scenario, ...
                "v2xsim.vehicle.scenario.VelocityBasedKinematicScenario"));
        end

        function testRejectsMismatchedVehicleSet(testCase)
            [kinematics, laneNetwork, laneStates] = ...
                testCase.createInputs();
            laneStates.Properties.RowNames{1} = 'other-vehicle';

            constructor = @() ...
                v2xsimtest.vehicle.scenario.fixture.LanedScenarioStub( ...
                    kinematics, laneNetwork, laneStates);

            testCase.verifyError( ...
                constructor, ...
                "v2xsim:scenario:LaneStateVehicleSetMismatch");
        end

        function testRejectsUnknownLane(testCase)
            [kinematics, laneNetwork, laneStates] = ...
                testCase.createInputs();
            laneStates.LaneId(1) = "unknown";

            constructor = @() ...
                v2xsimtest.vehicle.scenario.fixture.LanedScenarioStub( ...
                    kinematics, laneNetwork, laneStates);

            testCase.verifyError( ...
                constructor, ...
                "v2xsim:scenario:UnknownVehicleLane");
        end

        function testRejectsPositionOutsideAssignedCenterline(testCase)
            [kinematics, laneNetwork, laneStates] = ...
                testCase.createInputs();
            kinematics.X(1) = kinematics.X(1) + 1;

            constructor = @() ...
                v2xsimtest.vehicle.scenario.fixture.LanedScenarioStub( ...
                    kinematics, laneNetwork, laneStates);

            testCase.verifyError( ...
                constructor, ...
                "v2xsim:scenario:VehicleOutsideAssignedLane");
        end

        function testAllowsNonzeroLateralOffset(testCase)
            [kinematics, laneNetwork, laneStates] = ...
                testCase.createInputs();
            laneStates.LateralOffsetMeters(1) = 0.5;
            kinematics.X(1) = kinematics.X(1) + 0.25;

            scenario = ...
                v2xsimtest.vehicle.scenario.fixture.LanedScenarioStub( ...
                    kinematics, laneNetwork, laneStates);

            testCase.verifyEqual( ...
                scenario.VehicleLaneStates.LateralOffsetMeters(1), 0.5);
        end

        function testTracksVehiclesAcrossLaneSegmentTransition(testCase)
            scenario = ...
                v2xsimtest.vehicle.scenario.fixture.TwoSegmentLanedScenarioStub();
            expectedLaneIds = [ ...
                "first-segment", "second-segment", "second-segment"; ...
                "first-segment", "second-segment", "second-segment"];
            expectedProgress = [0.6, 0, 0.4; 0.95, 0, 0.05];

            for stepIndex = 1:3
                scenario = scenario.step(1);
                laneStates = scenario.VehicleLaneStates;
                positionsFromLaneState = scenario.LaneNetwork.evaluate( ...
                    laneStates.LaneId, laneStates.Progress);

                testCase.verifyEqual( ...
                    laneStates.LaneId, ...
                    expectedLaneIds(:, stepIndex));
                testCase.verifyEqual( ...
                    laneStates.Progress, ...
                    expectedProgress(:, stepIndex), ...
                    AbsTol=1e-12);
                testCase.verifyEqual( ...
                    laneStates.LateralOffsetMeters, zeros(2, 1));
                testCase.verifyEqual( ...
                    [scenario.VehicleKinematics.X, ...
                    scenario.VehicleKinematics.Y], ...
                    positionsFromLaneState, ...
                    AbsTol=1e-12);
            end
        end

        function testStepRejectsStaleLaneState(testCase)
            scenario = ...
                v2xsimtest.vehicle.scenario.fixture.TwoSegmentLanedScenarioStub( ...
                    ReturnStaleLaneStates=true);

            testCase.verifyError( ...
                @() scenario.step(1), ...
                "v2xsim:scenario:VehicleOutsideAssignedLane");
        end
    end

    methods (Access = private)
        function [kinematics, laneNetwork, laneStates] = ...
                createInputs(~)
            firstLane = ...
                v2xsim.vehicle.scenario.highway.ParametricLane( ...
                    3.5, @(progress) [10 .* progress, ...
                    zeros(size(progress))]);
            secondLane = ...
                v2xsim.vehicle.scenario.highway.ParametricLane( ...
                    3.5, @(progress) [10 .* progress, ...
                    4 .* ones(size(progress))]);
            laneNetwork = ...
                v2xsim.vehicle.scenario.highway.LaneNetwork( ...
                    ["first", "second"], {firstLane, secondLane});

            rowNames = ["vehicle-1", "vehicle-2"];
            laneId = ["first"; "second"];
            progress = [0.2; 0.8];
            lateralOffsetMeters = zeros(2, 1);
            positions = laneNetwork.evaluate(laneId, progress);
            zero = zeros(2, 1);
            unknown = NaN(2, 1);
            kinematics = table( ...
                positions(:, 1), positions(:, 2), ...
                zero, zero, unknown, unknown, ...
                VariableNames=["X", "Y", "vX", "vY", "aX", "aY"], ...
                RowNames=rowNames);
            laneStates = table( ...
                laneId, progress, lateralOffsetMeters, ...
                VariableNames=[ ...
                    "LaneId", "Progress", "LateralOffsetMeters"], ...
                RowNames=rowNames);
        end
    end
end
