classdef VelocityBasedKinematicScenarioTest < matlab.unittest.TestCase
    %VELOCITYBASEDKINEMATICSCENARIOTEST Tests velocity integration hooks.

    methods (Test)
        function testUpdatesVelocityThenIntegratesPosition(testCase)
            initialKinematics = testCase.createKinematics();
            scenario = ...
                v2xsimtest.vehicle.scenario.fixture.VelocityBasedKinematicScenarioStub( ...
                    initialKinematics, ...
                    VelocityDelta=[1, -2], ...
                    PositionCorrection=[100, 200]);

            [scenario, transitions] = scenario.step(2);

            testCase.verifyEqual( ...
                scenario.VehicleKinematics.vX, [3; 4]);
            testCase.verifyEqual( ...
                scenario.VehicleKinematics.vY, [2; 3]);
            testCase.verifyEqual( ...
                scenario.VehicleKinematics.X, [107; 118]);
            testCase.verifyEqual( ...
                scenario.VehicleKinematics.Y, [205; 216]);
            testCase.verifyEqual( ...
                transitions.Properties.RowNames, ...
                scenario.VehicleKinematics.Properties.RowNames);
        end

        function testIntegrationMatchesVehiclesByRowName(testCase)
            initialKinematics = testCase.createKinematics();
            scenario = ...
                v2xsimtest.vehicle.scenario.fixture.VelocityBasedKinematicScenarioStub( ...
                    initialKinematics, ...
                    ReorderDuringVelocityUpdate=true);

            scenario = scenario.step(2);

            testCase.verifyEqual( ...
                string(scenario.VehicleKinematics.Properties.RowNames), ...
                ["vehicle-2"; "vehicle-1"]);
            testCase.verifyEqual( ...
                scenario.VehicleKinematics.X, [16; 5]);
            testCase.verifyEqual( ...
                scenario.VehicleKinematics.Y, [20; 9]);
        end

        function testVelocityHookCannotChangePosition(testCase)
            scenario = ...
                v2xsimtest.vehicle.scenario.fixture.VelocityBasedKinematicScenarioStub( ...
                    testCase.createKinematics(), ...
                    ChangePositionDuringVelocityUpdate=true);

            testCase.verifyError( ...
                @() scenario.step(1), ...
                "v2xsim:scenario:VelocityUpdateChangedPosition");
        end
    end

    methods (Access = private)
        function vehicleKinematics = createKinematics(~)
            x = [1; 10];
            y = [1; 10];
            vX = [2; 3];
            vY = [4; 5];
            unknownAcceleration = NaN(2, 1);
            vehicleKinematics = table( ...
                x, y, vX, vY, ...
                unknownAcceleration, unknownAcceleration, ...
                VariableNames=["X", "Y", "vX", "vY", "aX", "aY"], ...
                RowNames=["vehicle-1", "vehicle-2"]);
        end
    end
end
