function [simParams,varargin] = initiatePositionErrorChain( ...
        simParams,fileCfg,varargin)
%INITIATEPOSITIONERRORCHAIN Parse an ordered positioning-error pipeline.
%   [positionErrorModules] is a comma-separated list containing Gaussian,
%   Delay, FalseExit, and/or FalseMerge. Module-specific options use the
%   positionErrorOptions.<Module>.<Option> namespace.

[simParams,varargin] = addNewParam( ...
    simParams,'positionErrorModules','None', ...
    'Ordered position error modules','string',fileCfg,varargin{1});
moduleNames = parseModuleNames(simParams.positionErrorModules);

usesExitRampContext = any(ismember( ...
    moduleNames,["FalseExit","FalseMerge"]));
if usesExitRampContext && ...
        ~strcmp(simParams.typeOfScenario,'ExitRampHighwayScenario')
    error( ...
        'v2xsim:legacy:IncompatiblePositionErrorModule', ...
        ['FalseExit and FalseMerge position errors require ', ...
        'ExitRampHighwayScenario.']);
end

modules = cell(1,numel(moduleNames));
for moduleIndex = 1:numel(moduleNames)
    switch moduleNames(moduleIndex)
        case "Gaussian"
            [simParams,varargin] = addNewParam( ...
                simParams, ...
                'positionErrorOptions.Gaussian.StandardDeviationMeters', ...
                0,'Gaussian radial standard deviation (m)', ...
                'double',fileCfg,varargin{1});
            modules{moduleIndex} = ...
                v2xsim.positioning.IsotropicGaussianPositionError( ...
                    simParams.positionErrorOptions.Gaussian. ...
                        StandardDeviationMeters);

        case "Delay"
            [simParams,varargin] = addNewParam( ...
                simParams, ...
                'positionErrorOptions.Delay.DelaySeconds', ...
                0,'Position observation delay (s)', ...
                'double',fileCfg,varargin{1});
            modules{moduleIndex} = ...
                v2xsim.positioning.PositionDelayError( ...
                    simParams.positionErrorOptions.Delay.DelaySeconds);

        case "FalseExit"
            [simParams,remainingArguments] = parseFalseRouteOptions( ...
                simParams,fileCfg,varargin{1},"FalseExit");
            varargin = {remainingArguments};
            options = simParams.positionErrorOptions.FalseExit;
            modules{moduleIndex} = ...
                v2xsim.positioning.FalseExitPositionError( ...
                    options.CurseProbability, ...
                    ResetAfterSeconds=options.ResetAfterSeconds);

        case "FalseMerge"
            [simParams,remainingArguments] = parseFalseRouteOptions( ...
                simParams,fileCfg,varargin{1},"FalseMerge");
            varargin = {remainingArguments};
            options = simParams.positionErrorOptions.FalseMerge;
            modules{moduleIndex} = ...
                v2xsim.positioning.FalseMergePositionError( ...
                    options.CurseProbability, ...
                    ResetAfterSeconds=options.ResetAfterSeconds);
    end
end

simParams.positionErrorModuleNames = moduleNames;
simParams.positionErrorChain = ...
    v2xsim.positioning.PositionErrorChain(modules);
end

function moduleNames = parseModuleNames(configuredValue)
configuredValue = string(configuredValue);
if ~isscalar(configuredValue)
    error( ...
        'v2xsim:legacy:InvalidPositionErrorModules', ...
        '[positionErrorModules] must be one comma-separated string.');
end

configuredValue = strip(configuredValue);
if strlength(configuredValue)==0 || strcmpi(configuredValue,"None")
    moduleNames = strings(1,0);
    return
end

configuredNames = strip(split(configuredValue,","));
moduleNames = strings(size(configuredNames));
for moduleIndex = 1:numel(configuredNames)
    normalizedName = lower(regexprep( ...
        configuredNames(moduleIndex),'[^a-zA-Z0-9]',''));
    switch normalizedName
        case {"gaussian","isotropicgaussian", ...
                "isotropicgaussianpositionerror"}
            moduleNames(moduleIndex) = "Gaussian";
        case {"delay","positiondelay","positiondelayerror"}
            moduleNames(moduleIndex) = "Delay";
        case {"falseexit","falseexitpositionerror"}
            moduleNames(moduleIndex) = "FalseExit";
        case {"falsemerge","falsemergepositionerror"}
            moduleNames(moduleIndex) = "FalseMerge";
        otherwise
            error( ...
                'v2xsim:legacy:UnknownPositionErrorModule', ...
                ['Unknown position error module "%s". Supported ', ...
                'modules are Gaussian, Delay, FalseExit, and ', ...
                'FalseMerge.'],configuredNames(moduleIndex));
    end
end
moduleNames = reshape(moduleNames,1,[]);

if numel(unique(moduleNames))~=numel(moduleNames)
    error( ...
        'v2xsim:legacy:DuplicatePositionErrorModule', ...
        ['Each position error module type may appear at most once ', ...
        'in [positionErrorModules].']);
end
end

function [simParams,remainingArguments] = parseFalseRouteOptions( ...
        simParams,fileCfg,remainingArguments,moduleName)
probabilityField = sprintf( ...
    'positionErrorOptions.%s.CurseProbability',moduleName);
resetField = sprintf( ...
    'positionErrorOptions.%s.ResetAfterSeconds',moduleName);
[simParams,wrappedArguments] = addNewParam( ...
    simParams,probabilityField,0, ...
    sprintf('%s curse probability',moduleName), ...
    'double',fileCfg,remainingArguments);
remainingArguments = wrappedArguments{1};
[simParams,wrappedArguments] = addNewParam( ...
    simParams,resetField,Inf, ...
    sprintf('%s reset duration (s)',moduleName), ...
    'double',fileCfg,remainingArguments);
remainingArguments = wrappedArguments{1};
end
