classdef BidirectionalHighwayScenarioTest < matlab.unittest.TestCase
    %BIDIRECTIONALHIGHWAYSCENARIOTEST Tests highway motion invariants.

    methods (Test)
        function testDefaultsCreateValidHighway(testCase)
            randomStream = RandStream("mt19937ar", Seed=100);

            scenario = ...
                v2xsim.vehicle.scenarios.BidirectionalHighwayScenario( ...
                    200, RandomStream=randomStream);
            kinematics = scenario.VehicleKinematics;

            testCase.verifyEqual(scenario.NLanes, 1);
            testCase.verifyEqual(scenario.LaneWidth, 2.5);
            testCase.verifyEqual(scenario.RoadLength, 2000);
            testCase.verifyEqual(scenario.CentralDividerWidth, 0);
            testCase.verifyEqual(scenario.MeanVehicleSpeed, 80);
            testCase.verifyEqual( ...
                scenario.VehicleSpeedStandardDeviation, 10);
            testCase.verifyTrue(scenario.RerollSpeedOnWrapAround);
            testCase.verifyClass( ...
                scenario.Geometry, ...
                "v2xsim.vehicle.scenario.highway.Geometry");
            testCase.verifyClass( ...
                scenario.PlacementStrategy, ...
                "v2xsim.vehicle.scenario.highway.placement.Random");
            testCase.verifyClass( ...
                scenario.MobilityModel, ...
                "v2xsim.vehicle.scenario.highway.mobility.RerollingSpeed");
            testCase.verifyEqual(height(kinematics), 200);
            testCase.verifyGreaterThanOrEqual(kinematics.X, 0);
            testCase.verifyLessThanOrEqual(kinematics.X, 2000);
            testCase.verifyEqual(kinematics.vY, zeros(200, 1));
            testCase.verifyEqual(abs(kinematics.Y), 1.25 .* ones(200, 1));
            testCase.verifyEqual(sign(kinematics.vX), sign(kinematics.Y));
        end

        function testVehiclesSpawnAtValidLaneCenters(testCase)
            randomStream = RandStream("mt19937ar", Seed=200);
            nLanes = 4;
            laneWidth = 3.5;
            dividerWidth = 2;
            expectedAbsoluteY = ...
                dividerWidth ./ 2 + ((1:nLanes) - 0.5) .* laneWidth;

            scenario = ...
                v2xsim.vehicle.scenarios.BidirectionalHighwayScenario( ...
                    1000, ...
                    RandomStream=randomStream, ...
                    NLanes=nLanes, ...
                    LaneWidth=laneWidth, ...
                    CentralDividerWidth=dividerWidth);
            actualAbsoluteY = abs(scenario.VehicleKinematics.Y);

            testCase.verifyTrue(all( ...
                ismember(actualAbsoluteY, expectedAbsoluteY)));
        end

        function testLaneInvariantsHoldAcrossManyWraps(testCase)
            randomStream = RandStream("mt19937ar", Seed=300);
            scenario = ...
                v2xsim.vehicle.scenarios.BidirectionalHighwayScenario( ...
                    250, ...
                    RandomStream=randomStream, ...
                    NLanes=3, ...
                    LaneWidth=3, ...
                    RoadLength=50, ...
                    CentralDividerWidth=1, ...
                    MeanVehicleSpeed=80, ...
                    VehicleSpeedStandardDeviation=10, ...
                    RerollSpeedOnWrapAround=true);
            initialY = scenario.VehicleKinematics.Y;

            for stepIndex = 1:20
                scenario = scenario.step(0.75);
                kinematics = scenario.VehicleKinematics;

                testCase.verifyEqual(kinematics.Y, initialY, ...
                    sprintf("Y changed at step %d.", stepIndex));
                testCase.verifyEqual(kinematics.vY, zeros(250, 1), ...
                    sprintf("vY was nonzero at step %d.", stepIndex));
                testCase.verifyGreaterThanOrEqual(kinematics.X, 0);
                testCase.verifyLessThanOrEqual(kinematics.X, 50);
            end
        end

        function testDisabledRerollPreservesSpeedAndWrapsPosition(testCase)
            randomStream = RandStream("mt19937ar", Seed=400);
            scenario = ...
                v2xsim.vehicle.scenarios.BidirectionalHighwayScenario( ...
                    100, ...
                    RandomStream=randomStream, ...
                    RoadLength=25, ...
                    RerollSpeedOnWrapAround=false);
            initialKinematics = scenario.VehicleKinematics;
            deltaTime = 10;
            expectedX = mod( ...
                initialKinematics.X + initialKinematics.vX .* deltaTime, ...
                scenario.RoadLength);

            scenario = scenario.step(deltaTime);

            testCase.verifyEqual(scenario.VehicleKinematics.X, expectedX, ...
                AbsTol=1e-12);
            testCase.verifyEqual( ...
                abs(scenario.VehicleKinematics.vX), ...
                abs(initialKinematics.vX));
            testCase.verifyEqual( ...
                scenario.VehicleKinematics.Y, initialKinematics.Y);
        end

        function testEnabledRerollChangesSpeedAfterWrapping(testCase)
            randomStream = RandStream("mt19937ar", Seed=500);
            scenario = ...
                v2xsim.vehicle.scenarios.BidirectionalHighwayScenario( ...
                    50, ...
                    RandomStream=randomStream, ...
                    RoadLength=0.01, ...
                    MeanVehicleSpeed=10, ...
                    VehicleSpeedStandardDeviation=2, ...
                    RerollSpeedOnWrapAround=true);
            initialSpeed = abs(scenario.VehicleKinematics.vX);

            scenario = scenario.step(0.1);
            finalSpeed = abs(scenario.VehicleKinematics.vX);

            testCase.verifyTrue(any(finalSpeed ~= initialSpeed));
        end

        function testExplicitStreamsMakeInitializationRepeatable(testCase)
            firstStream = RandStream("mt19937ar", Seed=600);
            secondStream = RandStream("mt19937ar", Seed=600);

            firstScenario = ...
                v2xsim.vehicle.scenarios.BidirectionalHighwayScenario( ...
                    100, RandomStream=firstStream, NLanes=2);
            secondScenario = ...
                v2xsim.vehicle.scenarios.BidirectionalHighwayScenario( ...
                    100, RandomStream=secondStream, NLanes=2);

            testCase.verifyEqual( ...
                firstScenario.VehicleKinematics, ...
                secondScenario.VehicleKinematics);
        end
    end
end
