classdef BrownianMotionScenarioTest < matlab.unittest.TestCase
    %BROWNIANMOTIONSCENARIOTEST Smoke tests BrownianMotionScenario.

    methods (Test)
        function testDefaultsCreateValidScenario(testCase)
            randomStream = RandStream("mt19937ar", Seed=1234);

            scenario = v2xsim.vehicle.scenarios.BrownianMotionScenario( ...
                100, RandomStream=randomStream);
            kinematics = scenario.VehicleKinematics;

            testCase.verifyEqual(height(kinematics), 100);
            testCase.verifyEqual(scenario.SimulationAreaSize, 1000);
            testCase.verifyEqual(scenario.MeanVehicleSpeed, 50);
            testCase.verifyEqual( ...
                scenario.VehicleSpeedStandardDeviation, 10);
            testCase.verifyGreaterThanOrEqual(kinematics.X, 0);
            testCase.verifyLessThanOrEqual(kinematics.X, 1000);
            testCase.verifyGreaterThanOrEqual(kinematics.Y, 0);
            testCase.verifyLessThanOrEqual(kinematics.Y, 1000);
            testCase.verifyTrue(all(isfinite(kinematics.vX)));
            testCase.verifyTrue(all(isfinite(kinematics.vY)));
            testCase.verifyTrue(all(isnan(kinematics.aX)));
            testCase.verifyTrue(all(isnan(kinematics.aY)));
            testCase.verifyEqual( ...
                numel(kinematics.Properties.RowNames), 100);
        end

        function testExplicitStreamsMakeInitializationRepeatable(testCase)
            firstStream = RandStream("mt19937ar", Seed=42);
            secondStream = RandStream("mt19937ar", Seed=42);

            firstScenario = ...
                v2xsim.vehicle.scenarios.BrownianMotionScenario( ...
                    20, RandomStream=firstStream);
            secondScenario = ...
                v2xsim.vehicle.scenarios.BrownianMotionScenario( ...
                    20, RandomStream=secondStream);

            testCase.verifyEqual( ...
                firstScenario.VehicleKinematics, ...
                secondScenario.VehicleKinematics);
        end

        function testStepReflectsAndPreservesVehicleIdentities(testCase)
            import v2xsim.vehicle.scenario.VehicleLifecycleTransition

            randomStream = RandStream("mt19937ar", Seed=7);
            scenario = v2xsim.vehicle.scenarios.BrownianMotionScenario( ...
                50, ...
                RandomStream=randomStream, ...
                SimulationAreaSize=10, ...
                MeanVehicleSpeed=20, ...
                VehicleSpeedStandardDeviation=5);
            initialKinematics = scenario.VehicleKinematics;
            initialSpeed = hypot( ...
                initialKinematics.vX, initialKinematics.vY);

            [scenario, transitions] = scenario.step(100);
            finalKinematics = scenario.VehicleKinematics;
            finalSpeed = hypot(finalKinematics.vX, finalKinematics.vY);

            testCase.verifyGreaterThanOrEqual(finalKinematics.X, 0);
            testCase.verifyLessThanOrEqual(finalKinematics.X, 10);
            testCase.verifyGreaterThanOrEqual(finalKinematics.Y, 0);
            testCase.verifyLessThanOrEqual(finalKinematics.Y, 10);
            testCase.verifyEqual(finalSpeed, initialSpeed, ...
                AbsTol=1e-12);
            testCase.verifyEqual( ...
                sort(string(finalKinematics.Properties.RowNames)), ...
                sort(string(initialKinematics.Properties.RowNames)));
            testCase.verifyEqual( ...
                string(transitions.Properties.RowNames), ...
                string(finalKinematics.Properties.RowNames));
            testCase.verifyTrue(all( ...
                transitions.Transition == ...
                VehicleLifecycleTransition.Unchanged));
        end

        function testBackwardStepIsReversible(testCase)
            randomStream = RandStream("mt19937ar", Seed=99);
            scenario = v2xsim.vehicle.scenarios.BrownianMotionScenario( ...
                25, ...
                RandomStream=randomStream, ...
                SimulationAreaSize=100, ...
                MeanVehicleSpeed=10, ...
                VehicleSpeedStandardDeviation=2);
            initialKinematics = scenario.VehicleKinematics;

            scenario = scenario.step(3.25);
            scenario = scenario.step(-3.25);

            testCase.verifyEqual( ...
                scenario.VehicleKinematics{:, :}, ...
                initialKinematics{:, :}, ...
                AbsTol=1e-12);
            testCase.verifyEqual( ...
                scenario.VehicleKinematics.Properties.RowNames, ...
                initialKinematics.Properties.RowNames);
        end
    end
end
