classdef EtsiHighwayScenarioTest < matlab.unittest.TestCase
    %ETSIHIGHWAYSCENARIOTEST Tests ETSI freeway density invariants.

    methods (TestMethodSetup)
        function preserveGlobalRandomStream(testCase)
            randomStream = RandStream.getGlobalStream();
            originalState = randomStream.State;
            testCase.addTeardown( ...
                @() restoreRandomStreamState(randomStream, originalState));
        end
    end

    methods (Test)
        function testFixedFreewayGeometry(testCase)
            import v2xsim.vehicle.scenarios.etsihighway.TrafficModel

            scenario = v2xsim.vehicle.scenarios.EtsiHighwayScenario( ...
                TrafficModel.HighSpeedLowDensity);

            testCase.verifyClass(scenario, ...
                "v2xsim.vehicle.scenarios.EtsiHighwayScenario");
            testCase.verifyTrue(isa(scenario, ...
                "v2xsim.vehicle.scenario.highway.HighwayScenario"));
            testCase.verifyTrue(isa(scenario, ...
                "v2xsim.vehicle.scenario.VelocityBasedKinematicScenario"));
            testCase.verifyTrue(isa( ...
                scenario, "v2xsim.vehicle.scenario.LanedScenario"));
            testCase.verifyClass( ...
                scenario.PlacementStrategy, ...
                "v2xsim.vehicle.scenario.highway.placement.UniformHeadway");
            testCase.verifyClass( ...
                scenario.MobilityModel, ...
                "v2xsim.vehicle.scenario.highway.mobility.ConstantSpeed");
            testCase.verifyEqual(scenario.NLanes, 3);
            testCase.verifyEqual(scenario.LaneWidth, 4);
            testCase.verifyEqual(scenario.CentralDividerWidth, 0);
            expectedRoadLength = ...
                ceil(2000 ./ scenario.TargetAverageHeadway) .* ...
                scenario.TargetAverageHeadway;
            testCase.verifyEqual(scenario.RoadLength, expectedRoadLength, ...
                AbsTol=1e-12);
            testCase.verifyGreaterThanOrEqual(scenario.RoadLength, 2000);
            testCase.verifyFalse(scenario.RerollSpeedOnWrapAround);
            testCase.verifyEqual(scenario.LaneNetwork.LaneCount, 6);
            laneStates = scenario.VehicleLaneStates;
            testCase.verifyEqual( ...
                [scenario.VehicleKinematics.X, ...
                scenario.VehicleKinematics.Y], ...
                scenario.LaneNetwork.evaluate( ...
                    laneStates.LaneId, laneStates.Progress), ...
                AbsTol=1e-10);
            testCase.verifyEqual( ...
                unique(abs(scenario.VehicleKinematics.Y)), ...
                [2; 6; 10]);
        end

        function testTrafficModelsExposeSpecifiedTargets(testCase)
            import v2xsim.vehicle.scenarios.etsihighway.TrafficModel

            models = [ ...
                TrafficModel.HighSpeedLowDensity, ...
                TrafficModel.MediumSpeedMediumDensity, ...
                TrafficModel.LowSpeedHighDensity];
            expectedSpeeds = [250, 140, 70];
            expectedHeadways = [173.6, 97.2, 48.6];

            for modelIndex = 1:numel(models)
                scenario = v2xsim.vehicle.scenarios.EtsiHighwayScenario( ...
                    models(modelIndex));

                testCase.verifyEqual( ...
                    scenario.AverageVehicleSpeedKilometersPerHour, ...
                    expectedSpeeds(modelIndex));
                testCase.verifyEqual( ...
                    scenario.TargetAverageHeadway, ...
                    expectedHeadways(modelIndex), ...
                    AbsTol=0.05);
                testCase.verifyEqual( ...
                    abs(scenario.VehicleKinematics.vX), ...
                    expectedSpeeds(modelIndex) ./ 3.6 .* ...
                    ones(height(scenario.VehicleKinematics), 1), ...
                    AbsTol=1e-12);
            end
        end

        function testUniformPlacementDoesNotConsumeRandomNumbers(testCase)
            import v2xsim.vehicle.scenarios.etsihighway.Placement
            import v2xsim.vehicle.scenarios.etsihighway.TrafficModel

            randomStream = RandStream.getGlobalStream();
            stateBeforeConstruction = randomStream.State;

            v2xsim.vehicle.scenarios.EtsiHighwayScenario( ...
                TrafficModel.HighSpeedLowDensity, ...
                Placement=Placement.Uniform);

            testCase.verifyEqual( ...
                randomStream.State, stateBeforeConstruction);
        end

        function testUniformPlacementHasExactCircularHeadway(testCase)
            import v2xsim.vehicle.scenarios.etsihighway.Placement
            import v2xsim.vehicle.scenarios.etsihighway.TrafficModel

            models = [ ...
                TrafficModel.HighSpeedLowDensity, ...
                TrafficModel.MediumSpeedMediumDensity, ...
                TrafficModel.LowSpeedHighDensity];

            for model = models
                targetHeadway = model.TargetAverageHeadway;
                roadLength = ceil(2000 ./ targetHeadway) .* targetHeadway;
                scenario = v2xsim.vehicle.scenarios.EtsiHighwayScenario( ...
                    model, ...
                    Placement=Placement.Uniform, ...
                    MinimumRoadLength=roadLength);

                testCase.verifyClass( ...
                    scenario.PlacementStrategy, ...
                    "v2xsim.vehicle.scenario.highway.placement.UniformHeadway");

                laneHeadways = testCase.getCircularLaneHeadways(scenario);
                testCase.verifyEqual(laneHeadways, ...
                    targetHeadway .* ones(size(laneHeadways)), ...
                    AbsTol=1e-10);
            end
        end

        function testGaussianPlacementHasSpecifiedMeanHeadway(testCase)
            import v2xsim.vehicle.scenarios.etsihighway.Placement
            import v2xsim.vehicle.scenarios.etsihighway.TrafficModel

            model = TrafficModel.LowSpeedHighDensity;
            targetHeadway = model.TargetAverageHeadway;
            roadLength = 100 .* targetHeadway;
            scenario = v2xsim.vehicle.scenarios.EtsiHighwayScenario( ...
                model, ...
                Placement=Placement.Gaussian, ...
                MinimumRoadLength=roadLength);

            testCase.verifyClass( ...
                scenario.PlacementStrategy, ...
                "v2xsim.vehicle.scenario.highway.placement.GaussianHeadway");

            laneHeadways = testCase.getCircularLaneHeadways(scenario);
            testCase.verifyEqual(mean(laneHeadways), targetHeadway, ...
                AbsTol=1e-10);
            testCase.verifyGreaterThan(std(laneHeadways), 0);
        end

        function testDefaultRoadUsesSmallestCompatibleLength(testCase)
            import v2xsim.vehicle.scenarios.etsihighway.TrafficModel

            model = TrafficModel.HighSpeedLowDensity;
            scenario = v2xsim.vehicle.scenarios.EtsiHighwayScenario(model);
            expectedVehiclesPerLane = ...
                ceil(2000 ./ model.TargetAverageHeadway);

            testCase.verifyEqual( ...
                scenario.VehiclesPerLane, expectedVehiclesPerLane);
            testCase.verifyEqual(scenario.MinimumRoadLength, 2000);
            testCase.verifyEqual( ...
                scenario.RoadLength, ...
                expectedVehiclesPerLane .* model.TargetAverageHeadway, ...
                AbsTol=1e-12);
            testCase.verifyEqual( ...
                mean(testCase.getCircularLaneHeadways(scenario)), ...
                model.TargetAverageHeadway, ...
                AbsTol=1e-12);
        end

        function testArbitraryMinimumRoadLengthRoundsUp(testCase)
            import v2xsim.vehicle.scenarios.etsihighway.TrafficModel

            minimumRoadLength = 2345;
            model = TrafficModel.HighSpeedLowDensity;
            scenario = v2xsim.vehicle.scenarios.EtsiHighwayScenario( ...
                model, MinimumRoadLength=minimumRoadLength);

            testCase.verifyEqual( ...
                scenario.MinimumRoadLength, minimumRoadLength);
            testCase.verifyGreaterThanOrEqual( ...
                scenario.RoadLength, minimumRoadLength);
            testCase.verifyLessThan( ...
                scenario.RoadLength - minimumRoadLength, ...
                model.TargetAverageHeadway);
            testCase.verifyEqual( ...
                scenario.RoadLength, ...
                scenario.VehiclesPerLane .* model.TargetAverageHeadway, ...
                AbsTol=1e-12);
        end

        function testVehiclesRemainInLanesAfterWrapping(testCase)
            import v2xsim.vehicle.scenarios.etsihighway.TrafficModel

            scenario = v2xsim.vehicle.scenarios.EtsiHighwayScenario( ...
                TrafficModel.LowSpeedHighDensity);
            initialY = scenario.VehicleKinematics.Y;
            initialHeadways = ...
                sort(testCase.getCircularLaneHeadways(scenario));

            scenario = scenario.step(1000);

            testCase.verifyEqual(scenario.VehicleKinematics.Y, initialY);
            testCase.verifyEqual( ...
                scenario.VehicleKinematics.vY, ...
                zeros(height(scenario.VehicleKinematics), 1));
            testCase.verifyGreaterThanOrEqual( ...
                scenario.VehicleKinematics.X, 0);
            testCase.verifyLessThanOrEqual( ...
                scenario.VehicleKinematics.X, scenario.RoadLength);
            testCase.verifyEqual( ...
                sort(testCase.getCircularLaneHeadways(scenario)), ...
                initialHeadways, ...
                AbsTol=1e-10);
        end

        function testRejectsRoadShorterThanTwoKilometers(testCase)
            import v2xsim.vehicle.scenarios.etsihighway.TrafficModel

            constructor = @() ...
                v2xsim.vehicle.scenarios.EtsiHighwayScenario( ...
                    TrafficModel.HighSpeedLowDensity, ...
                    MinimumRoadLength=1999);

            testCase.verifyFunctionThrows(constructor);
        end
    end

    methods (Access = private)
        function headways = getCircularLaneHeadways(~, scenario)
            kinematics = scenario.VehicleKinematics;
            laneCenters = unique(kinematics.Y);
            headways = zeros(height(kinematics), 1);
            nextHeadwayIndex = 1;

            for laneCenter = laneCenters.'
                laneX = sort(kinematics.X(kinematics.Y == laneCenter));
                laneHeadways = diff([laneX; laneX(1) + scenario.RoadLength]);
                indices = nextHeadwayIndex:( ...
                    nextHeadwayIndex + numel(laneHeadways) - 1);
                headways(indices) = laneHeadways;
                nextHeadwayIndex = ...
                    nextHeadwayIndex + numel(laneHeadways);
            end
        end

        function verifyFunctionThrows(testCase, functionHandle)
            didThrow = false;
            try
                functionHandle();
            catch
                didThrow = true;
            end

            testCase.verifyTrue(didThrow, ...
                "Expected the function to throw an exception.");
        end
    end
end

function restoreRandomStreamState(randomStream, state)
randomStream.State = state;
end
