classdef (Abstract) LanedScenario < ...
        v2xsim.vehicle.scenario.VelocityBasedKinematicScenario
    %LANEDSCENARIO Scenario exposing lane geometry and vehicle lane state.
    %   LaneNetwork is immutable. VehicleLaneStates identifies every
    %   vehicle by table row name and gives its LaneId, normalized Progress,
    %   and LateralOffsetMeters. Each integration step resolves kinematics
    %   and lane state together so the two views cannot become stale.

    properties (SetAccess = immutable)
        LaneNetwork (1, 1) ...
            v2xsim.vehicle.scenario.highway.LaneNetwork = ...
            v2xsim.vehicle.scenario.highway.LaneNetwork()
    end

    properties (SetAccess = private)
        VehicleLaneStates table ...
            {v2xsim.vehicle.scenario.validation.mustBeVehicleLaneStateTable} = ...
            table( ...
                strings(0, 1), zeros(0, 1), zeros(0, 1), ...
                VariableNames=[ ...
                    "LaneId", "Progress", "LateralOffsetMeters"])
    end

    methods (Access = protected)
        function obj = LanedScenario( ...
                initialVehicleKinematics, laneNetwork, ...
                initialVehicleLaneStates)
            arguments (Input)
                initialVehicleKinematics table ...
                    {v2xsim.vehicle.scenario.validation.mustBe2DKinematicsTable}
                laneNetwork (1, 1) ...
                    v2xsim.vehicle.scenario.highway.LaneNetwork
                initialVehicleLaneStates table ...
                    {v2xsim.vehicle.scenario.validation.mustBeVehicleLaneStateTable}
            end

            if laneNetwork.LaneCount == 0
                error( ...
                    "v2xsim:scenario:LaneNetworkEmpty", ...
                    "A laned scenario must expose at least one lane.");
            end

            obj = obj@v2xsim.vehicle.scenario.VelocityBasedKinematicScenario( ...
                initialVehicleKinematics);
            obj.LaneNetwork = laneNetwork;
            obj = obj.updateVehicleLaneStates( ...
                initialVehicleLaneStates, initialVehicleKinematics);
        end

        function obj = updateVehicleLaneStates( ...
                obj, vehicleLaneStates, vehicleKinematics)
            arguments (Input)
                obj (1, 1)
                vehicleLaneStates table ...
                    {v2xsim.vehicle.scenario.validation.mustBeVehicleLaneStateTable}
                vehicleKinematics table ...
                    {v2xsim.vehicle.scenario.validation.mustBe2DKinematicsTable}
            end

            kinematicVehicleIds = string( ...
                vehicleKinematics.Properties.RowNames);
            laneStateVehicleIds = string( ...
                vehicleLaneStates.Properties.RowNames);
            if ~isequal( ...
                    sort(kinematicVehicleIds), ...
                    sort(laneStateVehicleIds))
                error( ...
                    "v2xsim:scenario:LaneStateVehicleSetMismatch", ...
                    "Vehicle lane-state row names must match vehicle " + ...
                    "kinematics row names.");
            end

            vehicleLaneStates = vehicleLaneStates( ...
                vehicleKinematics.Properties.RowNames, :);
            unknownLanes = ~obj.LaneNetwork.hasLane( ...
                vehicleLaneStates.LaneId);
            if any(unknownLanes)
                error( ...
                    "v2xsim:scenario:UnknownVehicleLane", ...
                    "Vehicle lane state references unknown lane(s): %s.", ...
                    join(unique( ...
                        vehicleLaneStates.LaneId(unknownLanes)), ", "));
            end

            onCenterline = vehicleLaneStates.LateralOffsetMeters == 0;
            expectedPositions = obj.LaneNetwork.evaluate( ...
                vehicleLaneStates.LaneId(onCenterline), ...
                vehicleLaneStates.Progress(onCenterline));
            actualPositions = [ ...
                vehicleKinematics.X(onCenterline), ...
                vehicleKinematics.Y(onCenterline)];
            tolerance = 1e-9 .* max( ...
                [1; abs(expectedPositions(:)); abs(actualPositions(:))]);
            if any( ...
                    abs(expectedPositions - actualPositions) > tolerance, ...
                    "all")
                error( ...
                    "v2xsim:scenario:VehicleOutsideAssignedLane", ...
                    "A zero-offset vehicle position must equal its " + ...
                    "assigned lane centerline at the reported progress.");
            end

            obj.VehicleLaneStates = vehicleLaneStates;
        end
    end

    methods (Sealed, Access = protected)
        function [obj, vehicleKinematics] = resolvePositionConstraints( ...
                obj, previousVehicleKinematics, vehicleKinematics, ...
                deltaTime)
            previousVehicleLaneStates = obj.VehicleLaneStates;
            [obj, vehicleKinematics, vehicleLaneStates] = ...
                obj.resolveLanedPositionConstraints( ...
                    previousVehicleKinematics, ...
                    vehicleKinematics, ...
                    previousVehicleLaneStates, ...
                    deltaTime);
            obj = obj.updateVehicleLaneStates( ...
                vehicleLaneStates, vehicleKinematics);
        end
    end

    methods (Abstract, Access = protected)
        %RESOLVELANEDPOSITIONCONSTRAINTS Resolve kinematics and lane state.
        %   Implementations must return one lane-state row for every
        %   vehicle. LanedScenario validates and commits both views
        %   atomically after this hook returns.
        [obj, vehicleKinematics, vehicleLaneStates] = ...
            resolveLanedPositionConstraints( ...
                obj, previousVehicleKinematics, vehicleKinematics, ...
                previousVehicleLaneStates, deltaTime)
    end
end
