classdef (Abstract) VelocityBasedKinematicScenario < ...
        v2xsim.vehicle.scenario.Scenario
    %VELOCITYBASEDKINEMATICSCENARIO Integrate positions from velocity.
    %   Subclasses may update vehicle velocities before each integration
    %   step and resolve position constraints afterward. This class is for
    %   fixed-vehicle scenarios whose positions obey
    %
    %       nextPosition = currentPosition + velocity * deltaTime.

    properties (Constant)
        IS_VEHICLE_COUNT_DYNAMIC = false
        PROVIDES_VELOCITY = true
    end

    methods (Access = protected)
        function obj = VelocityBasedKinematicScenario( ...
                initialVehicleKinematics)
            arguments (Input)
                initialVehicleKinematics table ...
                    {v2xsim.vehicle.scenario.validation.mustBe2DKinematicsTable}
            end

            obj = obj@v2xsim.vehicle.scenario.Scenario( ...
                initialVehicleKinematics);
        end
    end

    methods (Sealed, Access = protected)
        function [obj, vehicleKinematics, vehicleLifecycleTransitions] = ...
                doStep(obj, deltaTime)
            previousVehicleKinematics = obj.VehicleKinematics;

            [obj, vehicleKinematics] = obj.updateVelocities( ...
                previousVehicleKinematics, deltaTime);
            previousVehicleKinematics = ...
                v2xsim.vehicle.scenario.VelocityBasedKinematicScenario.validateVelocityUpdate( ...
                    previousVehicleKinematics, vehicleKinematics);

            vehicleKinematics.X = ...
                previousVehicleKinematics.X + ...
                vehicleKinematics.vX .* deltaTime;
            vehicleKinematics.Y = ...
                previousVehicleKinematics.Y + ...
                vehicleKinematics.vY .* deltaTime;

            [obj, vehicleKinematics] = obj.resolvePositionConstraints( ...
                previousVehicleKinematics, ...
                vehicleKinematics, ...
                deltaTime);
            v2xsim.vehicle.scenario.VelocityBasedKinematicScenario.validateResolvedKinematics( ...
                previousVehicleKinematics, vehicleKinematics);

            import v2xsim.vehicle.scenario.VehicleLifecycleTransition

            transition = repmat( ...
                VehicleLifecycleTransition.Unchanged, ...
                height(vehicleKinematics), 1);
            vehicleLifecycleTransitions = table( ...
                transition, ...
                VariableNames="Transition", ...
                RowNames=vehicleKinematics.Properties.RowNames);
        end
    end

    methods (Access = protected)
        function [obj, vehicleKinematics] = updateVelocities( ...
                obj, vehicleKinematics, ~)
            %UPDATEVELOCITIES Update velocity commands before integration.
            %   The default implementation retains the current velocities.
            %   Overrides must preserve positions and vehicle identities.
        end

        function [obj, vehicleKinematics] = resolvePositionConstraints( ...
                obj, ~, vehicleKinematics, ~)
            %RESOLVEPOSITIONCONSTRAINTS Correct the integrated state.
            %   The default implementation applies no position constraint.
            %   Overrides may wrap, reflect, snap, or teleport vehicles and
            %   may update velocity in response to those operations.
        end
    end

    methods (Static, Access = private)
        function previousVehicleKinematics = validateVelocityUpdate( ...
                previousVehicleKinematics, vehicleKinematics)
            v2xsim.vehicle.scenario.validation.mustBe2DKinematicsTable( ...
                vehicleKinematics);
            previousVehicleKinematics = ...
                v2xsim.vehicle.scenario.VelocityBasedKinematicScenario.alignAndValidateVehicleSet( ...
                    previousVehicleKinematics, ...
                    vehicleKinematics, ...
                    "v2xsim:scenario:VelocityUpdateChangedVehicleSet");

            changedPosition = ...
                ~isequaln(previousVehicleKinematics.X, ...
                    vehicleKinematics.X) || ...
                ~isequaln(previousVehicleKinematics.Y, ...
                    vehicleKinematics.Y);
            if changedPosition
                error( ...
                    "v2xsim:scenario:VelocityUpdateChangedPosition", ...
                    "updateVelocities must not change X or Y. Use " + ...
                    "resolvePositionConstraints for position changes.");
            end

            unavailableVelocity = ...
                any(~isfinite(vehicleKinematics.vX)) || ...
                any(~isfinite(vehicleKinematics.vY));
            if unavailableVelocity
                error( ...
                    "v2xsim:scenario:VelocityUnavailable", ...
                    "A velocity-based scenario must provide finite vX " + ...
                    "and vY values for every vehicle.");
            end
        end

        function validateResolvedKinematics( ...
                previousVehicleKinematics, vehicleKinematics)
            v2xsim.vehicle.scenario.validation.mustBe2DKinematicsTable( ...
                vehicleKinematics);
            v2xsim.vehicle.scenario.VelocityBasedKinematicScenario.alignAndValidateVehicleSet( ...
                previousVehicleKinematics, ...
                vehicleKinematics, ...
                "v2xsim:scenario:PositionResolutionChangedVehicleSet");
        end

        function referenceKinematics = alignAndValidateVehicleSet( ...
                referenceKinematics, candidateKinematics, errorId)
            candidateRowNames = ...
                candidateKinematics.Properties.RowNames;
            if isempty(candidateRowNames) || ...
                    numel(candidateRowNames) ~= height(candidateKinematics)
                error( ...
                    "v2xsim:scenario:MissingVehicleRowNames", ...
                    "VehicleKinematics must have one unique row name " + ...
                    "for every vehicle.");
            end

            referenceRowNames = string( ...
                referenceKinematics.Properties.RowNames);
            hasSameVehicles = isequal( ...
                sort(referenceRowNames), ...
                sort(string(candidateRowNames)));
            if ~hasSameVehicles
                error( ...
                    errorId, ...
                    "Velocity-based integration must preserve the set " + ...
                    "of vehicle row names.");
            end

            referenceKinematics = referenceKinematics( ...
                candidateRowNames, :);
        end
    end
end
