classdef BidirectionalHighwayScenario < ...
        v2xsim.vehicle.scenario.highway.HighwayScenario
    %BIDIRECTIONALHIGHWAYSCENARIO Random straight two-way highway.
    %   Vehicles spawn at uniformly random X positions and in random lanes.
    %   Positive-Y lanes travel in +X, negative-Y lanes travel in -X, and
    %   vehicles periodically wrap around the longitudinal road boundary.

    methods
        function obj = BidirectionalHighwayScenario(vehicleCount, options)
            arguments (Input)
                vehicleCount (1, 1) double ...
                    {mustBeInteger, mustBePositive}
                options.RandomStream (1, 1) RandStream = ...
                    RandStream.getGlobalStream()
                options.NLanes (1, 1) double ...
                    {mustBeInteger, mustBePositive} = 1
                options.LaneWidth (1, 1) double ...
                    {mustBeReal, mustBeFinite, mustBePositive} = 2.5
                options.RoadLength (1, 1) double ...
                    {mustBeReal, mustBeFinite, mustBePositive} = 2000
                options.CentralDividerWidth (1, 1) double ...
                    {mustBeReal, mustBeFinite, mustBeNonnegative} = 0
                options.MeanVehicleSpeed (1, 1) double ...
                    {mustBeReal, mustBeFinite, mustBeNonnegative} = 80
                options.VehicleSpeedStandardDeviation (1, 1) double ...
                    {mustBeReal, mustBeFinite, mustBeNonnegative} = 10
                options.RerollSpeedOnWrapAround (1, 1) logical = true
            end

            geometry = v2xsim.vehicle.scenario.highway.Geometry( ...
                options.NLanes, ...
                options.LaneWidth, ...
                options.RoadLength, ...
                options.CentralDividerWidth);
            placementStrategy = ...
                v2xsim.vehicle.scenario.highway.placement.Random( ...
                    vehicleCount);
            mobilityModel = ...
                v2xsim.vehicle.scenario.highway.mobility.RerollingSpeed( ...
                    options.MeanVehicleSpeed, ...
                    options.VehicleSpeedStandardDeviation, ...
                    RerollSpeedOnWrapAround= ...
                        options.RerollSpeedOnWrapAround, ...
                    RandomStream=options.RandomStream);

            obj = obj@v2xsim.vehicle.scenario.highway.HighwayScenario( ...
                geometry, ...
                placementStrategy, ...
                mobilityModel, ...
                options.RandomStream);
        end
    end
end
