classdef EtsiHighwayScenario < ...
        v2xsim.vehicle.scenario.highway.HighwayScenario
    %ETSIHIGHWAYSCENARIO ETSI freeway vehicle drop and mobility model.
    %   Implements the freeway case in 3GPP TR 38.913 V18.0.0,
    %   Table 6.1.9-2: three 4 m lanes per direction, a freeway length of
    %   at least 2000 m with wraparound, and average same-lane headway equal
    %   to 2.5 seconds multiplied by the absolute vehicle speed.
    %
    %   MinimumRoadLength specifies the requested simulation scale. The
    %   actual RoadLength is the smallest integer multiple of the traffic
    %   model's target headway that is at least MinimumRoadLength.

    properties (Constant)
        % Defined in 3GPP TR 38.913.
        ETSI_NUMBER_OF_LANES_PER_DIRECTION = 3
        ETSI_LANE_WIDTH = 4
        MINIMUM_ROAD_LENGTH = 2000

        % Model assumptions not defined in 3GPP TR 38.913.
        ETSI_CENTRAL_DIVIDER_WIDTH = 0
        GAUSSIAN_HEADWAY_COEFFICIENT_OF_VARIATION = 1 / 3
    end

    properties (SetAccess = immutable)
        TrafficModel (1, 1) ...
            v2xsim.vehicle.scenarios.etsihighway.TrafficModel
        Placement (1, 1) ...
            v2xsim.vehicle.scenarios.etsihighway.Placement
        TargetAverageHeadway (1, 1) double ...
            {mustBeFinite, mustBeReal, mustBePositive} = 1
        VehiclesPerLane (1, 1) double ...
            {mustBeInteger, mustBeReal, mustBePositive} = 1
        MinimumRoadLength (1, 1) double ...
            {mustBeFinite, mustBeReal, mustBePositive} = 2000
        AverageVehicleSpeedKilometersPerHour (1, 1) double
    end

    methods
        function obj = EtsiHighwayScenario(trafficModel, options)
            arguments (Input)
                trafficModel (1, 1) ...
                    v2xsim.vehicle.scenarios.etsihighway.TrafficModel
                options.Placement (1, 1) ...
                    v2xsim.vehicle.scenarios.etsihighway.Placement = ...
                    v2xsim.vehicle.scenarios.etsihighway.Placement.Uniform
                options.MinimumRoadLength (1, 1) double ...
                    {mustBeReal, mustBeFinite, ...
                    mustBeGreaterThanOrEqual( ...
                        options.MinimumRoadLength, ...
                        2000)} = 2000
            end

            targetAverageHeadway = trafficModel.TargetAverageHeadway;
            vehicleCountRatio = ...
                options.MinimumRoadLength ./ targetAverageHeadway;
            nearestIntegerVehicleCount = round(vehicleCountRatio);
            if abs(vehicleCountRatio - nearestIntegerVehicleCount) <= ...
                    16 .* eps(vehicleCountRatio)
                vehiclesPerLane = nearestIntegerVehicleCount;
            else
                vehiclesPerLane = ceil(vehicleCountRatio);
            end
            roadLength = vehiclesPerLane .* targetAverageHeadway;
            averageSpeedMetersPerSecond = ...
                trafficModel.AverageVehicleSpeedKilometersPerHour ./ 3.6;
            randomStream = RandStream.getGlobalStream();

            geometry = v2xsim.vehicle.scenario.highway.Geometry( ...
                v2xsim.vehicle.scenarios.EtsiHighwayScenario.ETSI_NUMBER_OF_LANES_PER_DIRECTION, ...
                v2xsim.vehicle.scenarios.EtsiHighwayScenario.ETSI_LANE_WIDTH, ...
                roadLength, ...
                v2xsim.vehicle.scenarios.EtsiHighwayScenario.ETSI_CENTRAL_DIVIDER_WIDTH);

            import v2xsim.vehicle.scenarios.etsihighway.Placement
            if options.Placement == Placement.Uniform
                placementStrategy = ...
                    v2xsim.vehicle.scenario.highway.placement.UniformHeadway( ...
                        vehiclesPerLane);
            else
                placementStrategy = ...
                    v2xsim.vehicle.scenario.highway.placement.GaussianHeadway( ...
                        vehiclesPerLane, ...
                        CoefficientOfVariation= ...
                            v2xsim.vehicle.scenarios.EtsiHighwayScenario.GAUSSIAN_HEADWAY_COEFFICIENT_OF_VARIATION);
            end

            mobilityModel = ...
                v2xsim.vehicle.scenario.highway.mobility.ConstantSpeed( ...
                    averageSpeedMetersPerSecond);

            obj = obj@v2xsim.vehicle.scenario.highway.HighwayScenario( ...
                geometry, ...
                placementStrategy, ...
                mobilityModel, ...
                randomStream);

            obj.TrafficModel = trafficModel;
            obj.Placement = options.Placement;
            obj.TargetAverageHeadway = targetAverageHeadway;
            obj.VehiclesPerLane = vehiclesPerLane;
            obj.MinimumRoadLength = options.MinimumRoadLength;
            obj.AverageVehicleSpeedKilometersPerHour = ...
                trafficModel.AverageVehicleSpeedKilometersPerHour;
        end
    end
end
