classdef ExitRampHighwayScenario < ...
        v2xsim.vehicle.scenario.highway.HighwayScenario
    %EXITRAMPHIGHWAYSCENARIO Left-driving highway with symmetric exits.
    %   The outermost lane in each direction reaches a fork at
    %   X=RoadLength/2. The exit branch bends 45 degrees to the driver's
    %   left and reaches the normal X boundary; its physical length from
    %   fork to endpoint is RoadLength/sqrt(2). A vehicle that does not
    %   exit transitions to the adjacent lane over MergeDistance. Setting
    %   MergeDistance to zero makes this transition an immediate snap.
    %
    %   Vehicles retain a fixed home lane. An outer-home-lane vehicle is
    %   recycled to the upstream outer lane after reaching either the ramp
    %   endpoint or the downstream mainline boundary.

    properties (Dependent, SetAccess = private)
        ExitProbability
        MergeDistance
        VehicleRouteStates
    end

    methods
        function obj = ExitRampHighwayScenario(vehicleCount, options)
            arguments (Input)
                vehicleCount (1, 1) double ...
                    {mustBeInteger, mustBePositive}
                options.RandomStream (1, 1) RandStream = ...
                    RandStream.getGlobalStream()
                options.NLanes (1, 1) double ...
                    {mustBeInteger, mustBePositive} = 2
                options.LaneWidth (1, 1) double ...
                    {mustBeReal, mustBeFinite, mustBePositive} = 2.5
                options.RoadLength (1, 1) double ...
                    {mustBeReal, mustBeFinite, mustBePositive} = 2000
                options.CentralDividerWidth (1, 1) double ...
                    {mustBeReal, mustBeFinite, mustBeNonnegative} = 0
                options.MeanVehicleSpeed (1, 1) double ...
                    {mustBeReal, mustBeFinite, mustBeNonnegative} = 80
                options.VehicleSpeedStandardDeviation (1, 1) double ...
                    {mustBeReal, mustBeFinite, mustBeNonnegative} = 10
                options.RerollSpeedOnWrapAround (1, 1) logical = true
                options.ExitProbability (1, 1) double ...
                    {mustBeReal, mustBeFinite, mustBeNonnegative} = 0.5
                options.MergeDistance (1, 1) double ...
                    {mustBeReal, mustBeFinite, mustBeNonnegative} = 100
            end

            if options.ExitProbability > 1
                error( ...
                    "v2xsim:scenario:highway:InvalidExitProbability", ...
                    "ExitProbability must lie between zero and one, " + ...
                    "inclusive.");
            end

            geometry = ...
                v2xsim.vehicle.scenario.highway.ExitRampGeometry( ...
                    options.NLanes, ...
                    options.LaneWidth, ...
                    options.RoadLength, ...
                    options.CentralDividerWidth, ...
                    options.MergeDistance);
            placementStrategy = ...
                v2xsim.vehicle.scenario.highway.placement.ExitRampRandom( ...
                    vehicleCount, options.ExitProbability);
            mobilityModel = ...
                v2xsim.vehicle.scenario.highway.mobility.ExitRamp( ...
                    options.MeanVehicleSpeed, ...
                    options.VehicleSpeedStandardDeviation, ...
                    options.ExitProbability, ...
                    RerollSpeedOnWrapAround= ...
                        options.RerollSpeedOnWrapAround, ...
                    RandomStream=options.RandomStream);

            obj = obj@v2xsim.vehicle.scenario.highway.HighwayScenario( ...
                geometry, ...
                placementStrategy, ...
                mobilityModel, ...
                options.RandomStream);
        end

        function value = get.ExitProbability(obj)
            value = obj.MobilityModel.ExitProbability;
        end

        function value = get.MergeDistance(obj)
            value = obj.Geometry.MergeDistance;
        end

        function value = get.VehicleRouteStates(obj)
            routes = obj.MobilityModel.VehicleRoutes;
            value = routes(:, ["TravelDirection", "Route"]);
        end
    end
end
