classdef ExitRampPositionErrorContextTest < matlab.unittest.TestCase
    %EXITRAMPPOSITIONERRORCONTEXTTEST Tests ramp-specific context contracts.

    methods (Test)
        function testCapturesExitRampScenarioSnapshot(testCase)
            scenario = testCase.createScenario();

            context = ...
                v2xsim.positioning.ExitRampPositionErrorContext( ...
                    scenario, 2.5, 0.1, 10);

            testCase.verifyTrue(isa( ...
                context, "v2xsim.positioning.PositionErrorContext"));
            testCase.verifyEqual( ...
                context.ActualPositions, ...
                scenario.VehicleKinematics(:, ["X", "Y"]));
            testCase.verifyEqual(context.Geometry, scenario.Geometry);
            testCase.verifyEqual( ...
                context.LaneNetwork, scenario.LaneNetwork);
            testCase.verifyEqual( ...
                context.VehicleLaneStates, ...
                scenario.VehicleLaneStates);
            testCase.verifyEqual( ...
                context.VehicleRouteStates, ...
                scenario.VehicleRouteStates);
        end

        function testRampModuleAcceptsExitRampContext(testCase)
            scenario = testCase.createScenario();
            context = ...
                v2xsim.positioning.ExitRampPositionErrorContext( ...
                    scenario, 0, 0.1, 10);
            module = ...
                v2xsimtest.positioning.fixture.ExitRampPositionErrorModuleStub();

            [~, apparentPositions] = module.apply( ...
                context.ActualPositions, context);

            testCase.verifyEqual( ...
                apparentPositions, context.ActualPositions);
        end

        function testRampModuleRejectsGenericContext(testCase)
            scenario = testCase.createScenario();
            actualPositions = ...
                scenario.VehicleKinematics(:, ["X", "Y"]);
            context = v2xsim.positioning.PositionErrorContext( ...
                actualPositions, 0, 0.1, 10);
            module = ...
                v2xsimtest.positioning.fixture.ExitRampPositionErrorModuleStub();

            testCase.verifyError( ...
                @() module.apply(actualPositions, context), ...
                "v2xsim:positioning:UnsupportedErrorContext");
        end
    end

    methods (Access = private)
        function scenario = createScenario(~)
            scenario = ...
                v2xsim.vehicle.scenarios.ExitRampHighwayScenario( ...
                    20, ...
                    RandomStream=RandStream("mt19937ar", Seed=100), ...
                    RoadLength=200, ...
                    MergeDistance=40);
        end
    end
end
