classdef FalseExitPositionErrorTest < matlab.unittest.TestCase
    %FALSEEXITPOSITIONERRORTEST Tests false exit-ramp observations.

    methods (Test)
        function testProjectsMergingVehiclesOntoRamp(testCase)
            scenario = testCase.createScenario(0, 40);
            context = testCase.createContext(scenario, 0, 20);
            apparentPositions = context.ActualPositions;
            apparentPositions.X = apparentPositions.X + 2;
            apparentPositions.Y = apparentPositions.Y - 3;
            module = v2xsim.positioning.FalseExitPositionError(1);
            affected = testCase.getAffectedVehicles(context);
            testCase.assertTrue(any(affected));

            [~, outputPositions] = module.apply( ...
                apparentPositions, context);

            falsePositions = testCase.getRampPositions( ...
                context, affected);
            testCase.verifyEqual( ...
                outputPositions.X(affected), ...
                falsePositions(:, 1) + 2, ...
                AbsTol=1e-12);
            testCase.verifyEqual( ...
                outputPositions.Y(affected), ...
                falsePositions(:, 2) - 3, ...
                AbsTol=1e-12);
            testCase.verifyEqual( ...
                outputPositions(~affected, :), ...
                apparentPositions(~affected, :));
        end

        function testZeroProbabilityLeavesPositionsUnchanged(testCase)
            scenario = testCase.createScenario(0, 40);
            context = testCase.createContext(scenario, 0, 10);
            module = v2xsim.positioning.FalseExitPositionError(0);

            [~, outputPositions] = module.apply( ...
                context.ActualPositions, context);

            testCase.verifyEqual( ...
                outputPositions, context.ActualPositions);
        end

        function testFiniteResetTeleportsVehiclesBackToTruth(testCase)
            scenario = testCase.createScenario(0, 40);
            module = v2xsim.positioning.FalseExitPositionError( ...
                1, ResetAfterSeconds=2);
            initialContext = testCase.createContext(scenario, 0, 10);
            affected = testCase.getAffectedVehicles(initialContext);
            testCase.assertTrue(any(affected));

            [module, falsePositions] = module.apply( ...
                initialContext.ActualPositions, initialContext);
            oneSecondContext = testCase.createContext(scenario, 1, 10);
            [module, beforeReset] = module.apply( ...
                oneSecondContext.ActualPositions, oneSecondContext);
            resetContext = testCase.createContext(scenario, 2, 10);
            [module, afterReset] = module.apply( ...
                resetContext.ActualPositions, resetContext);
            afterRepairContext = testCase.createContext(scenario, 3, 10);
            [~, afterRepair] = module.apply( ...
                afterRepairContext.ActualPositions, afterRepairContext);

            testCase.verifyNotEqual( ...
                falsePositions(affected, :), ...
                initialContext.ActualPositions(affected, :));
            testCase.verifyEqual( ...
                beforeReset(affected, :), ...
                falsePositions(affected, :), ...
                AbsTol=1e-12);
            testCase.verifyEqual( ...
                afterReset, resetContext.ActualPositions);
            testCase.verifyEqual( ...
                afterRepair, afterRepairContext.ActualPositions);
        end

        function testDefaultCurseDoesNotExpire(testCase)
            scenario = testCase.createScenario(0, 40);
            module = v2xsim.positioning.FalseExitPositionError(1);
            initialContext = testCase.createContext(scenario, 0, 20);
            affected = testCase.getAffectedVehicles(initialContext);
            testCase.assertTrue(any(affected));
            [module, initialOutput] = module.apply( ...
                initialContext.ActualPositions, initialContext);

            laterContext = testCase.createContext(scenario, 20, 20);
            [~, laterOutput] = module.apply( ...
                laterContext.ActualPositions, laterContext);

            testCase.verifyEqual( ...
                laterOutput(affected, :), ...
                initialOutput(affected, :), ...
                AbsTol=1e-12);
            testCase.verifyNotEqual( ...
                laterOutput(affected, :), ...
                laterContext.ActualPositions(affected, :));
        end

        function testResetTimerStartsAtRouteDivergence(testCase)
            scenario = testCase.createScenario(0, 40);
            initialRoutes = scenario.VehicleRouteStates;
            vehicleIndex = find(initialRoutes.Route == "Outer", 1);
            testCase.assertNotEmpty(vehicleIndex);
            rowName = initialRoutes.Properties.RowNames{vehicleIndex};
            speed = abs(scenario.VehicleKinematics.vX(vehicleIndex));
            direction = initialRoutes.TravelDirection(vehicleIndex);
            distanceToFork = direction .* ...
                (scenario.Geometry.ForkX - ...
                scenario.VehicleKinematics.X(vehicleIndex));
            timeToDivergence = distanceToFork ./ speed + 0.1;
            module = v2xsim.positioning.FalseExitPositionError( ...
                1, ResetAfterSeconds=1);

            initialContext = ...
                v2xsim.positioning.ExitRampPositionErrorContext( ...
                    scenario, 0, 0.1, timeToDivergence + 1);
            module = module.apply( ...
                initialContext.ActualPositions, initialContext);
            scenario = scenario.step(timeToDivergence);
            divergedContext = ...
                v2xsim.positioning.ExitRampPositionErrorContext( ...
                    scenario, timeToDivergence, 0.1, ...
                    timeToDivergence + 1);
            [~, outputPositions] = module.apply( ...
                divergedContext.ActualPositions, divergedContext);

            testCase.verifyTrue(ismember( ...
                divergedContext.VehicleRouteStates.Route(rowName), ...
                ["Merge", "Adjacent"]));
            testCase.verifyNotEqual( ...
                outputPositions(rowName, :), ...
                divergedContext.ActualPositions(rowName, :));
        end

        function testFractionalProbabilityIsDrawnOncePerVehicle(testCase)
            seed = 700;
            probability = 0.5;
            scenario = testCase.createScenario(0, 40);
            initialContext = testCase.createContext(scenario, 0, 10);
            routes = initialContext.VehicleRouteStates.Route;
            eligible = routes ~= "Regular";
            expectedCursed = false(height(routes), 1);
            expectedStream = RandStream("mt19937ar", Seed=seed);
            expectedCursed(eligible) = ...
                rand(expectedStream, nnz(eligible), 1) < probability;
            expectedAffected = expectedCursed & ...
                testCase.getAffectedVehicles(initialContext);
            module = v2xsim.positioning.FalseExitPositionError( ...
                probability, ...
                RandomStream=RandStream( ...
                    "mt19937ar", Seed=seed));

            [module, initialOutput] = module.apply( ...
                initialContext.ActualPositions, initialContext);
            laterContext = testCase.createContext(scenario, 0.1, 10);
            [~, laterOutput] = module.apply( ...
                laterContext.ActualPositions, laterContext);

            initiallyChanged = ...
                initialOutput.X ~= initialContext.ActualPositions.X | ...
                initialOutput.Y ~= initialContext.ActualPositions.Y;
            laterChanged = ...
                laterOutput.X ~= laterContext.ActualPositions.X | ...
                laterOutput.Y ~= laterContext.ActualPositions.Y;
            testCase.verifyEqual(initiallyChanged, expectedAffected);
            testCase.verifyEqual(laterChanged, expectedAffected);
        end

        function testRejectsProbabilityAboveOne(testCase)
            testCase.verifyError( ...
                @() v2xsim.positioning.FalseExitPositionError(1.1), ...
                "v2xsim:positioning:InvalidCurseProbability");
        end
    end

    methods (Access = private)
        function scenario = createScenario(~, exitProbability, mergeDistance)
            scenario = ...
                v2xsim.vehicle.scenarios.ExitRampHighwayScenario( ...
                    500, ...
                    RandomStream=RandStream("mt19937ar", Seed=500), ...
                    RoadLength=200, ...
                    MeanVehicleSpeed=20, ...
                    VehicleSpeedStandardDeviation=0, ...
                    RerollSpeedOnWrapAround=false, ...
                    ExitProbability=exitProbability, ...
                    MergeDistance=mergeDistance);
        end

        function context = createContext( ...
                ~, scenario, simulationTimeSeconds, durationSeconds)
            context = ...
                v2xsim.positioning.ExitRampPositionErrorContext( ...
                    scenario, simulationTimeSeconds, 0.1, ...
                    durationSeconds);
        end

        function affected = getAffectedVehicles(~, context)
            route = context.VehicleRouteStates.Route;
            affected = route == "Merge" | route == "Adjacent";
        end

        function positions = getRampPositions( ...
                ~, context, affected)
            geometry = context.Geometry;
            actualPositions = context.ActualPositions(affected, :);
            direction = ...
                context.VehicleRouteStates.TravelDirection(affected);
            distancePastFork = direction .* ...
                (actualPositions.X - geometry.ForkX);
            progress = distancePastFork ./ ...
                (geometry.RoadLength ./ 2);
            positions = context.LaneNetwork.evaluate( ...
                geometry.getRampLaneId(direction), progress);
        end
    end
end
