classdef FalseMergePositionErrorTest < matlab.unittest.TestCase
    %FALSEMERGEPOSITIONERRORTEST Tests false mainline-merge observations.

    methods (Test)
        function testProjectsExitingVehiclesOntoMergeRoute(testCase)
            scenario = testCase.createScenario(40);
            context = testCase.createContext(scenario);
            module = v2xsim.positioning.FalseMergePositionError(1);
            affected = context.VehicleRouteStates.Route == "Ramp";
            testCase.assertTrue(any(affected));

            [~, outputPositions] = module.apply( ...
                context.ActualPositions, context);

            expectedPositions = testCase.getMergePositions( ...
                context, affected);
            testCase.verifyEqual( ...
                [outputPositions.X(affected), ...
                outputPositions.Y(affected)], ...
                expectedPositions, ...
                AbsTol=1e-12);
            testCase.verifyEqual( ...
                outputPositions(~affected, :), ...
                context.ActualPositions(~affected, :));
        end

        function testZeroMergeDistanceUsesAdjacentLane(testCase)
            scenario = testCase.createScenario(0);
            context = testCase.createContext(scenario);
            module = v2xsim.positioning.FalseMergePositionError(1);
            affected = context.VehicleRouteStates.Route == "Ramp";
            testCase.assertTrue(any(affected));

            [~, outputPositions] = module.apply( ...
                context.ActualPositions, context);

            expectedPositions = testCase.getMergePositions( ...
                context, affected);
            testCase.verifyEqual( ...
                [outputPositions.X(affected), ...
                outputPositions.Y(affected)], ...
                expectedPositions, ...
                AbsTol=1e-12);
        end

        function testZeroProbabilityLeavesPositionsUnchanged(testCase)
            scenario = testCase.createScenario(40);
            context = testCase.createContext(scenario);
            module = v2xsim.positioning.FalseMergePositionError(0);

            [~, outputPositions] = module.apply( ...
                context.ActualPositions, context);

            testCase.verifyEqual( ...
                outputPositions, context.ActualPositions);
        end
    end

    methods (Access = private)
        function scenario = createScenario(~, mergeDistance)
            scenario = ...
                v2xsim.vehicle.scenarios.ExitRampHighwayScenario( ...
                    500, ...
                    RandomStream=RandStream("mt19937ar", Seed=600), ...
                    RoadLength=200, ...
                    MeanVehicleSpeed=20, ...
                    VehicleSpeedStandardDeviation=0, ...
                    RerollSpeedOnWrapAround=false, ...
                    ExitProbability=1, ...
                    MergeDistance=mergeDistance);
        end

        function context = createContext(~, scenario)
            context = ...
                v2xsim.positioning.ExitRampPositionErrorContext( ...
                    scenario, 0, 0.1, 10);
        end

        function positions = getMergePositions( ...
                ~, context, affected)
            geometry = context.Geometry;
            actualPositions = context.ActualPositions(affected, :);
            direction = ...
                context.VehicleRouteStates.TravelDirection(affected);
            distancePastFork = direction .* ...
                (actualPositions.X - geometry.ForkX);
            onConnector = false(height(actualPositions), 1);
            if geometry.MergeDistance > 0
                onConnector = ...
                    distancePastFork <= geometry.MergeDistance;
            end
            positions = zeros(height(actualPositions), 2);

            if any(onConnector)
                positions(onConnector, :) = ...
                    context.LaneNetwork.evaluate( ...
                        geometry.getMergeLaneId( ...
                            direction(onConnector)), ...
                        distancePastFork(onConnector) ./ ...
                            geometry.MergeDistance);
            end

            onAdjacent = ~onConnector;
            if any(onAdjacent)
                laneIds = geometry.getMainlineLaneId( ...
                    direction(onAdjacent), ...
                    (geometry.NLanes - 1) .* ...
                    ones(nnz(onAdjacent), 1));
                progress = actualPositions.X(onAdjacent) ./ ...
                    geometry.RoadLength;
                negativeDirection = direction(onAdjacent) < 0;
                progress(negativeDirection) = ...
                    1 - progress(negativeDirection);
                positions(onAdjacent, :) = ...
                    context.LaneNetwork.evaluate(laneIds, progress);
            end
        end
    end
end
