classdef IsotropicGaussianPositionErrorTest < matlab.unittest.TestCase
    %ISOTROPICGAUSSIANPOSITIONERRORTEST Tests Gaussian displacement.

    methods (Test)
        function testMatchesLegacyRadialGaussianFormula(testCase)
            seed = 42;
            standardDeviationMeters = 3;
            positions = testCase.createPositions();
            module = ...
                v2xsim.positioning.IsotropicGaussianPositionError( ...
                    standardDeviationMeters, ...
                    RandomStream=RandStream( ...
                        "mt19937ar", Seed=seed));
            expectedStream = RandStream("mt19937ar", Seed=seed);
            radialDisplacement = standardDeviationMeters .* ...
                randn(expectedStream, height(positions), 1);
            directionRadians = 2 .* pi .* ...
                rand(expectedStream, height(positions), 1);

            [~, actualPositions] = module.apply( ...
                positions, testCase.createContext(positions, 0));

            expectedPositions = positions;
            expectedPositions.X = expectedPositions.X + ...
                radialDisplacement .* cos(directionRadians);
            expectedPositions.Y = expectedPositions.Y + ...
                radialDisplacement .* sin(directionRadians);
            testCase.verifyEqual( ...
                actualPositions, expectedPositions, AbsTol=1e-12);
        end

        function testSuccessiveApplicationsDrawNewErrors(testCase)
            positions = testCase.createPositions();
            module = ...
                v2xsim.positioning.IsotropicGaussianPositionError( ...
                    1, ...
                    RandomStream=RandStream( ...
                        "mt19937ar", Seed=100));

            [module, firstPositions] = module.apply( ...
                positions, testCase.createContext(positions, 0));
            [~, secondPositions] = module.apply( ...
                positions, testCase.createContext(positions, 0.1));

            testCase.verifyNotEqual(firstPositions, secondPositions);
        end

        function testZeroDeviationIsIdentity(testCase)
            positions = testCase.createPositions();
            module = ...
                v2xsim.positioning.IsotropicGaussianPositionError(0);

            [~, actualPositions] = module.apply( ...
                positions, testCase.createContext(positions, 0));

            testCase.verifyEqual(actualPositions, positions);
        end
    end

    methods (Access = private)
        function positions = createPositions(~)
            positions = table( ...
                [10; 20], [30; 40], ...
                VariableNames=["X", "Y"], ...
                RowNames=["vehicle-1", "vehicle-2"]);
        end

        function context = createContext( ...
                ~, actualPositions, simulationTimeSeconds)
            context = v2xsim.positioning.PositionErrorContext( ...
                actualPositions, simulationTimeSeconds, 0.1, 10);
        end
    end
end
