function mustBeVehicleLaneStateTable(value)
%MUSTBEVEHICLELANESTATETABLE Validate vehicle coordinates within lanes.
%   The table must contain exactly LaneId, Progress, and
%   LateralOffsetMeters. Vehicle identities are stored as row names.

if ~istable(value)
    error( ...
        "v2xsim:scenario:MustBeVehicleLaneStateTable", ...
        "Vehicle lane state must be provided as a table.");
end

expectedVariables = [ ...
    "LaneId", "Progress", "LateralOffsetMeters"];
actualVariables = string(value.Properties.VariableNames);
if ~isequal(actualVariables, expectedVariables)
    error( ...
        "v2xsim:scenario:MustBeVehicleLaneStateTable", ...
        "Vehicle lane state must contain exactly LaneId, Progress, " + ...
        "and LateralOffsetMeters, in that order.");
end

if ~isstring(value.LaneId) || size(value.LaneId, 2) ~= 1 || ...
        any(ismissing(value.LaneId) | strlength(value.LaneId) == 0)
    error( ...
        "v2xsim:scenario:MustBeVehicleLaneStateTable", ...
        "LaneId must be a nonempty, nonmissing string column.");
end

if ~isa(value.Progress, "double") || ...
        size(value.Progress, 2) ~= 1 || ...
        ~isreal(value.Progress) || ...
        any(~isfinite(value.Progress) | ...
            value.Progress < 0 | value.Progress > 1)
    error( ...
        "v2xsim:scenario:MustBeVehicleLaneStateTable", ...
        "Progress must be a finite, real double column between zero " + ...
        "and one, inclusive.");
end

if ~isa(value.LateralOffsetMeters, "double") || ...
        size(value.LateralOffsetMeters, 2) ~= 1 || ...
        ~isreal(value.LateralOffsetMeters) || ...
        any(~isfinite(value.LateralOffsetMeters))
    error( ...
        "v2xsim:scenario:MustBeVehicleLaneStateTable", ...
        "LateralOffsetMeters must be a finite, real double column.");
end

rowNames = value.Properties.RowNames;
if height(value) > 0 && ...
        (isempty(rowNames) || numel(rowNames) ~= height(value))
    error( ...
        "v2xsim:scenario:MustBeVehicleLaneStateTable", ...
        "Vehicle lane state must provide one unique row name per vehicle.");
end
end
