function packetReceptionRatios = runEtsiHighwayDensitySweep( ...
        outputDirectory, technology, packetReceptionRatioColumn)
%RUNETSIHIGHWAYDENSITYSWEEP Run the three ETSI freeway traffic models.

arguments (Input)
    outputDirectory (1, 1) string
    technology (1, 1) string {mustBeMember(technology, ...
        ["LTE-V2X", "5G-V2X", "80211p"])}
    packetReceptionRatioColumn (1, 1) string
end

arguments (Output)
    packetReceptionRatios (3, 1) double
end

projectRoot = fileparts(fileparts(fileparts(fileparts( ...
    mfilename("fullpath")))));
sourceDirectory = fullfile(projectRoot, "src");
simulatorDirectory = fullfile(projectRoot, "old_src");
addpath(sourceDirectory);
addpath(simulatorDirectory);

configurationFile = fullfile( ...
    simulatorDirectory, ...
    "ConfigFiles", ...
    "EtsiHighwayMediumMode1.cfg");
trafficModels = [ ...
    "HighSpeedLowDensity", ...
    "MediumSpeedMediumDensity", ...
    "LowSpeedHighDensity"];

for trafficModel = trafficModels
    % The arguments are consumed by the command evaluated below.
    simulationArguments = { ...
        configurationFile, ...
        "Technology", technology, ...
        "simulationTime", 2, ...
        "scenarioOptions.TrafficModel", trafficModel, ...
        "outputFolder", outputDirectory, ...
        "printPacketReceptionRatio", false, ...
        "printUpdateDelay", false, ...
        "printPacketDelay", false, ...
        "printDataAge", false, ...
        "printNeighbors", false, ...
        "printCBR", false}; %#ok<NASGU>
    evalc("WiLabV2Xsim(simulationArguments{:});");
end

outputTable = readtable( ...
    fullfile(outputDirectory, "MainOut.xls"), ...
    FileType="text", ...
    Delimiter="\t", ...
    VariableNamingRule="preserve");
packetReceptionRatios = outputTable.(packetReceptionRatioColumn);
end
