classdef WorldRsuSmokeTest < matlab.unittest.TestCase
    %WORLDRSUSMOKETEST End-to-end smoke test with a fixed World RSU.

    properties (SetAccess = private)
        TemporaryDirectory (1,1) string
    end

    methods (TestClassSetup)
        function createTemporaryDirectory(testCase)
            temporaryFolder = testCase.applyFixture( ...
                matlab.unittest.fixtures.TemporaryFolderFixture);
            testCase.TemporaryDirectory = ...
                string(temporaryFolder.Folder);
        end
    end

    methods (Test)
        function testVehiclesAndRsuParticipateAsDistinct11pUes(testCase)
            output = testCase.runSimulation( ...
                "80211p","11p","hpDENM",0,"11p");

            testCase.verifyUeCounts(output,0,5);
        end

        function testCv2xRsuRunsWithVehiclePositionError(testCase)
            output = testCase.runSimulation( ...
                "LTE-V2X","LTE","CAM",20,"cv2x");

            testCase.verifyUeCounts(output,5,0);
        end
    end

    methods (Access = private)
        function output = runSimulation( ...
                testCase,technology,rsuTechnology,packetType, ...
                positionError95,testName)
            projectRoot = fileparts(fileparts(fileparts(fileparts( ...
                mfilename("fullpath")))));
            sourceDirectory = fullfile(projectRoot,"src");
            simulatorDirectory = fullfile(projectRoot,"old_src");
            addpath(sourceDirectory);
            addpath(simulatorDirectory);

            rsuConfigurationFile = fullfile( ...
                testCase.TemporaryDirectory,testName + "-one-rsu.cfg");
            writelines([ ...
                "[NumberOfRSUs] 1"
                "[Technology] " + rsuTechnology
                "[PacketType] " + packetType
                "[xLocation] 100"
                "[yLocation] 5"], ...
                rsuConfigurationFile);

            outputDirectory = fullfile( ...
                testCase.TemporaryDirectory,testName + "-output");
            configurationFile = fullfile( ...
                simulatorDirectory,"ConfigFiles", ...
                "EtsiHighwayMediumMode1.cfg");
            if positionError95>0
                algorithmArguments = { ...
                    "BRAlgorithm",2, ...
                    "posError95",positionError95};
            else
                algorithmArguments = cell(1,0);
            end
            baseSimulationArguments = { ...
                configurationFile, ...
                "seed",1, ...
                "Technology",technology, ...
                "simulationTime",0.2, ...
                "positionTimeResolution",0.1, ...
                "typeOfScenario","BidirectionalHighwayScenario", ...
                "scenarioOptions.VehicleCount",4, ...
                "scenarioOptions.RoadLength",200, ...
                "scenarioOptions.MeanVehicleSpeed",10, ...
                "scenarioOptions.VehicleSpeedStandardDeviation",0, ...
                "scenarioOptions.RerollSpeedOnWrapAround",false, ...
                "RSUcfg",rsuConfigurationFile, ...
                "outputFolder",outputDirectory, ...
                "printPacketReceptionRatio",false, ...
                "printUpdateDelay",false, ...
                "printPacketDelay",false, ...
                "printDataAge",false, ...
                "printNeighbors",false, ...
                "printPowerControl",false, ...
                "printHiddenNodeProb",false, ...
                "printCBR",false};
            simulationArguments = [ ...
                baseSimulationArguments,algorithmArguments]; %#ok<NASGU>

            evalc("WiLabV2Xsim(simulationArguments{:});");

            output = readtable( ...
                fullfile(outputDirectory,"MainOut.xls"), ...
                FileType="text", ...
                Delimiter="\t", ...
                VariableNamingRule="preserve");
        end

        function verifyUeCounts( ...
                testCase,output,expectedCv2xCount,expected11pCount)
            testCase.verifyEqual(height(output),1);
            testCase.verifyEqual( ...
                output.("Average UEs in the world C-V2X"), ...
                expectedCv2xCount);
            testCase.verifyEqual( ...
                output.("Average UEs in the world 11p"), ...
                expected11pCount);
            testCase.verifyEqual( ...
                output.("Average UEs in the world TOT"),5);
            testCase.verifyFalse(any(contains( ...
                string(output.Properties.VariableNames), ...
                "vehicles in the scenario", ...
                IgnoreCase=true)));
            testCase.verifyTrue(contains( ...
                string(output.("Sim (positionTimeResolution,Limits)")), ...
                "+1RSU"));
        end
    end
end
