classdef TwoSegmentLanedScenarioStub < ...
        v2xsim.vehicle.scenario.LanedScenario
    %TWOSEGMENTLANEDSCENARIOSTUB Lane-following scenario for lifecycle tests.

    properties (Constant)
        CAN_STEP_BACKWARD = false
        PROVIDES_ACCELERATION = false
    end

    properties (SetAccess = immutable)
        ReturnStaleLaneStates (1, 1) logical
    end

    methods
        function obj = TwoSegmentLanedScenarioStub(options)
            arguments (Input)
                options.ReturnStaleLaneStates (1, 1) logical = false
            end

            laneNetwork = ...
                v2xsimtest.vehicle.scenario.fixture.TwoSegmentLanedScenarioStub.createLaneNetwork();
            [initialVehicleKinematics, initialVehicleLaneStates] = ...
                v2xsimtest.vehicle.scenario.fixture.TwoSegmentLanedScenarioStub.createInitialState( ...
                    laneNetwork);

            obj = obj@v2xsim.vehicle.scenario.LanedScenario( ...
                initialVehicleKinematics, ...
                laneNetwork, ...
                initialVehicleLaneStates);
            obj.ReturnStaleLaneStates = options.ReturnStaleLaneStates;
        end
    end

    methods (Access = protected)
        function [obj, vehicleKinematics, vehicleLaneStates] = ...
                resolveLanedPositionConstraints( ...
                    obj, ~, vehicleKinematics, ...
                    previousVehicleLaneStates, ~)
            if obj.ReturnStaleLaneStates
                vehicleLaneStates = previousVehicleLaneStates;
                return
            end

            if any(vehicleKinematics.X < 0 | vehicleKinematics.X > 20)
                error( ...
                    "v2xsimtest:scenario:VehicleOutsideTestNetwork", ...
                    "Test vehicles must remain within the two segments.");
            end

            inSecondSegment = vehicleKinematics.X >= 10;
            laneId = repmat( ...
                "first-segment", height(vehicleKinematics), 1);
            laneId(inSecondSegment) = "second-segment";

            progress = vehicleKinematics.X ./ 10;
            progress(inSecondSegment) = ...
                (vehicleKinematics.X(inSecondSegment) - 10) ./ 10;
            lateralOffsetMeters = zeros(height(vehicleKinematics), 1);
            vehicleLaneStates = table( ...
                laneId, progress, lateralOffsetMeters, ...
                VariableNames=[ ...
                    "LaneId", "Progress", "LateralOffsetMeters"], ...
                RowNames=vehicleKinematics.Properties.RowNames);
        end
    end

    methods (Static, Access = private)
        function laneNetwork = createLaneNetwork()
            import v2xsim.vehicle.scenario.highway.LaneConnectionKind

            firstLane = ...
                v2xsim.vehicle.scenario.highway.ParametricLane( ...
                    3.5, @(progress) [ ...
                        10 .* progress, zeros(size(progress))]);
            secondLane = ...
                v2xsim.vehicle.scenario.highway.ParametricLane( ...
                    3.5, @(progress) [ ...
                        10 + 10 .* progress, zeros(size(progress))]);
            connections = table( ...
                "first-segment", "second-segment", ...
                LaneConnectionKind.Continuation, 1, 0, ...
                VariableNames=[ ...
                    "FromLaneId", "ToLaneId", "Kind", ...
                    "FromProgress", "ToProgress"]);
            laneNetwork = ...
                v2xsim.vehicle.scenario.highway.LaneNetwork( ...
                    ["first-segment", "second-segment"], ...
                    {firstLane, secondLane}, connections);
        end

        function [vehicleKinematics, vehicleLaneStates] = ...
                createInitialState(laneNetwork)
            rowNames = ["vehicle-1", "vehicle-2"];
            laneId = repmat("first-segment", 2, 1);
            progress = [0.2; 0.9];
            lateralOffsetMeters = zeros(2, 1);
            positions = laneNetwork.evaluate(laneId, progress);
            vehicleKinematics = table( ...
                positions(:, 1), positions(:, 2), ...
                [4; 0.5], zeros(2, 1), NaN(2, 1), NaN(2, 1), ...
                VariableNames=["X", "Y", "vX", "vY", "aX", "aY"], ...
                RowNames=rowNames);
            vehicleLaneStates = table( ...
                laneId, progress, lateralOffsetMeters, ...
                VariableNames=[ ...
                    "LaneId", "Progress", "LateralOffsetMeters"], ...
                RowNames=rowNames);
        end
    end
end
