classdef LaneNetwork
    %LANENETWORK Named collection of parametric highway lanes.
    %   Lane identifiers are unique strings. EVALUATE maps a lane ID and
    %   normalized progress for each vehicle to Cartesian centerline
    %   coordinates in meters.

    properties (SetAccess = immutable)
        LaneIds (1, :) string = strings(1, 0)
        Lanes (1, :) cell = cell(1, 0)
        Connections table = table( ...
            strings(0, 1), strings(0, 1), ...
            repmat( ...
                v2xsim.vehicle.scenario.highway.LaneConnectionKind.Continuation, ...
                0, 1), ...
            zeros(0, 1), zeros(0, 1), ...
            VariableNames=[ ...
                "FromLaneId", "ToLaneId", "Kind", ...
                "FromProgress", "ToProgress"])
    end

    properties (Dependent, SetAccess = private)
        LaneCount
    end

    methods
        function obj = LaneNetwork(laneIds, lanes, connections)
            arguments (Input)
                laneIds (1, :) string = strings(1, 0)
                lanes (1, :) cell = cell(1, 0)
                connections table = ...
                    v2xsim.vehicle.scenario.highway.LaneNetwork.createEmptyConnections()
            end

            if numel(laneIds) ~= numel(lanes)
                error( ...
                    "v2xsim:scenario:highway:LaneNetworkSizeMismatch", ...
                    "LaneIds and Lanes must contain the same number " + ...
                    "of elements.");
            end
            if any(ismissing(laneIds) | strlength(laneIds) == 0) || ...
                    numel(unique(laneIds)) ~= numel(laneIds)
                error( ...
                    "v2xsim:scenario:highway:InvalidLaneIds", ...
                    "Lane identifiers must be nonempty, nonmissing, " + ...
                    "and unique.");
            end

            for laneIndex = 1:numel(lanes)
                if ~isa(lanes{laneIndex}, ...
                        "v2xsim.vehicle.scenario.highway.Lane") || ...
                        ~isscalar(lanes{laneIndex})
                    error( ...
                        "v2xsim:scenario:highway:InvalidLane", ...
                        "Lane %d must be a scalar Lane object.", ...
                        laneIndex);
                end
            end

            obj.validateConnections(connections, laneIds);
            obj.LaneIds = laneIds;
            obj.Lanes = lanes;
            obj.Connections = connections;
        end

        function value = get.LaneCount(obj)
            value = numel(obj.LaneIds);
        end

        function hasLanes = hasLane(obj, laneIds)
            %HASLANE Return whether each identifier belongs to the network.
            arguments (Input)
                obj (1, 1)
                laneIds string
            end

            hasLanes = ismember(laneIds, obj.LaneIds);
        end

        function lane = getLane(obj, laneId)
            %GETLANE Return the lane having the requested identifier.
            arguments (Input)
                obj (1, 1)
                laneId (1, 1) string
            end

            laneIndex = find(obj.LaneIds == laneId, 1);
            if isempty(laneIndex)
                error( ...
                    "v2xsim:scenario:highway:UnknownLane", ...
                    "Lane network does not contain lane '%s'.", laneId);
            end

            lane = obj.Lanes{laneIndex};
        end

        function connections = getOutgoingConnections(obj, laneId)
            %GETOUTGOINGCONNECTIONS Return connections leaving one lane.
            arguments (Input)
                obj (1, 1)
                laneId (1, 1) string
            end

            if ~obj.hasLane(laneId)
                error( ...
                    "v2xsim:scenario:highway:UnknownLane", ...
                    "Lane network does not contain lane '%s'.", laneId);
            end

            connections = obj.Connections( ...
                obj.Connections.FromLaneId == laneId, :);
        end

        function cartesianPositions = evaluate( ...
                obj, laneIds, progress)
            %EVALUATE Convert named lane coordinates to Cartesian positions.
            arguments (Input)
                obj (1, 1)
                laneIds (:, 1) string
                progress (:, 1) double ...
                    {mustBeReal, mustBeFinite}
            end

            if numel(laneIds) ~= numel(progress)
                error( ...
                    "v2xsim:scenario:highway:LaneCoordinateSizeMismatch", ...
                    "LaneIds and Progress must contain the same number " + ...
                    "of elements.");
            end
            if any(ismissing(laneIds) | strlength(laneIds) == 0)
                error( ...
                    "v2xsim:scenario:highway:InvalidLaneIds", ...
                    "Lane identifiers must be nonempty and nonmissing.");
            end

            cartesianPositions = zeros(numel(progress), 2);
            requestedLaneIds = unique(laneIds, "stable");
            for laneId = requestedLaneIds.'
                vehicleIndices = laneIds == laneId;
                lane = obj.getLane(laneId);
                cartesianPositions(vehicleIndices, :) = ...
                    lane.evaluate(progress(vehicleIndices));
            end
        end
    end

    methods (Static)
        function connections = createEmptyConnections()
            %CREATEEMPTYCONNECTIONS Create an empty fixed-schema table.
            kind = repmat( ...
                v2xsim.vehicle.scenario.highway.LaneConnectionKind.Continuation, ...
                0, 1);
            connections = table( ...
                strings(0, 1), strings(0, 1), kind, ...
                zeros(0, 1), zeros(0, 1), ...
                VariableNames=[ ...
                    "FromLaneId", "ToLaneId", "Kind", ...
                    "FromProgress", "ToProgress"]);
        end
    end

    methods (Static, Access = private)
        function validateConnections(connections, laneIds)
            expectedVariables = [ ...
                "FromLaneId", "ToLaneId", "Kind", ...
                "FromProgress", "ToProgress"];
            if ~isequal( ...
                    string(connections.Properties.VariableNames), ...
                    expectedVariables)
                error( ...
                    "v2xsim:scenario:highway:InvalidLaneConnections", ...
                    "Connections must contain exactly FromLaneId, " + ...
                    "ToLaneId, Kind, FromProgress, and ToProgress.");
            end

            if ~isstring(connections.FromLaneId) || ...
                    ~isstring(connections.ToLaneId) || ...
                    size(connections.FromLaneId, 2) ~= 1 || ...
                    size(connections.ToLaneId, 2) ~= 1 || ...
                    any(ismissing(connections.FromLaneId) | ...
                        strlength(connections.FromLaneId) == 0) || ...
                    any(ismissing(connections.ToLaneId) | ...
                        strlength(connections.ToLaneId) == 0)
                error( ...
                    "v2xsim:scenario:highway:InvalidLaneConnections", ...
                    "Connection lane identifiers must be nonempty, " + ...
                    "nonmissing string columns.");
            end

            validKind = isa( ...
                connections.Kind, ...
                "v2xsim.vehicle.scenario.highway.LaneConnectionKind") && ...
                size(connections.Kind, 2) == 1;
            validProgress = ...
                v2xsim.vehicle.scenario.highway.LaneNetwork.isValidProgressColumn( ...
                    connections.FromProgress) && ...
                v2xsim.vehicle.scenario.highway.LaneNetwork.isValidProgressColumn( ...
                    connections.ToProgress);
            knownLanes = all(ismember( ...
                [connections.FromLaneId; connections.ToLaneId], laneIds));
            if ~validKind || ~validProgress || ~knownLanes
                error( ...
                    "v2xsim:scenario:highway:InvalidLaneConnections", ...
                    "Every connection must have a valid kind, progress " + ...
                    "values in [0,1], and known source and target lanes.");
            end
        end

        function isValid = isValidProgressColumn(value)
            isValid = isa(value, "double") && ...
                size(value, 2) == 1 && isreal(value) && ...
                all(isfinite(value) & value >= 0 & value <= 1);
        end
    end
end
