classdef InitVehiclePositionsTest < matlab.unittest.TestCase
    %INITVEHICLEPOSITIONSTEST Tests Scenario-to-legacy initialization.

    methods (TestClassSetup)
        function addCompatibilityPaths(testCase)
            projectRoot = fileparts(fileparts(fileparts(fileparts( ...
                mfilename("fullpath")))));
            pathsToAdd = [ ...
                fullfile(projectRoot,"old_src","MatFilesInit"), ...
                fullfile(projectRoot,"old_src","MatFilesPosition")];
            for pathToAdd = pathsToAdd
                addpath(pathToAdd);
                testCase.addTeardown(@() rmpath(pathToAdd));
            end
        end
    end

    methods (Test)
        function testInitializesBrownianScenario(testCase)
            [~,simValues,positionManagement] = ...
                testCase.initializeScenario( ...
                    "BrownianMotionScenario",{ ...
                    "scenarioOptions.VehicleCount",25, ...
                    "scenarioOptions.SimulationAreaSize",500, ...
                    "scenarioOptions.MeanVehicleSpeed",40, ...
                    "scenarioOptions.VehicleSpeedStandardDeviation",5});

            testCase.verifyClass( ...
                simValues.world.TrafficScenario, ...
                "v2xsim.vehicle.scenarios.BrownianMotionScenario");
            testCase.verifyEqual( ...
                simValues.world.TrafficScenario.SimulationAreaSize,500);
            testCase.verifyEqual(positionManagement.Xmin,0);
            testCase.verifyEqual(positionManagement.Xmax,500);
            testCase.verifyEqual(positionManagement.Ymin,0);
            testCase.verifyEqual(positionManagement.Ymax,500);
            testCase.verifyProjection(simValues,positionManagement);
        end

        function testInitializesBidirectionalHighwayScenario(testCase)
            [~,simValues,positionManagement] = ...
                testCase.initializeScenario( ...
                    "BidirectionalHighwayScenario",{ ...
                    "scenarioOptions.VehicleCount",30, ...
                    "scenarioOptions.NLanes",3, ...
                    "scenarioOptions.LaneWidth",4, ...
                    "scenarioOptions.RoadLength",800, ...
                    "scenarioOptions.CentralDividerWidth",2, ...
                    "scenarioOptions.MeanVehicleSpeed",20, ...
                    "scenarioOptions.VehicleSpeedStandardDeviation",0, ...
                    "scenarioOptions.RerollSpeedOnWrapAround",false});

            scenario = simValues.world.TrafficScenario;
            testCase.verifyClass( ...
                scenario, ...
                "v2xsim.vehicle.scenarios.BidirectionalHighwayScenario");
            testCase.verifyEqual(scenario.NLanes,3);
            testCase.verifyEqual(scenario.LaneWidth,4);
            testCase.verifyEqual(scenario.RoadLength,800);
            testCase.verifyEqual(positionManagement.Xmin,0);
            testCase.verifyEqual(positionManagement.Xmax,800);
            testCase.verifyEqual(positionManagement.Ymin,-11);
            testCase.verifyEqual(positionManagement.Ymax,11);
            testCase.verifyProjection(simValues,positionManagement);
        end

        function testInitializesEtsiHighwayScenario(testCase)
            [~,simValues,positionManagement] = ...
                testCase.initializeScenario( ...
                    "EtsiHighwayScenario",{ ...
                    "scenarioOptions.TrafficModel", ...
                        "LowSpeedHighDensity", ...
                    "scenarioOptions.Placement","Gaussian", ...
                    "scenarioOptions.MinimumRoadLength",2500});

            import v2xsim.vehicle.scenarios.etsihighway.Placement
            import v2xsim.vehicle.scenarios.etsihighway.TrafficModel

            scenario = simValues.world.TrafficScenario;
            testCase.verifyClass( ...
                scenario,"v2xsim.vehicle.scenarios.EtsiHighwayScenario");
            testCase.verifyEqual( ...
                scenario.TrafficModel,TrafficModel.LowSpeedHighDensity);
            testCase.verifyEqual(scenario.Placement,Placement.Gaussian);
            testCase.verifyGreaterThanOrEqual(scenario.RoadLength,2500);
            testCase.verifyEqual(positionManagement.Xmax,scenario.RoadLength);
            testCase.verifyEqual(positionManagement.Ymin,-10);
            testCase.verifyEqual(positionManagement.Ymax,10);
            testCase.verifyProjection(simValues,positionManagement);
        end

        function testInitializesExitRampScenario(testCase)
            [~,simValues,positionManagement] = ...
                testCase.initializeScenario( ...
                    "ExitRampHighwayScenario",{ ...
                    "scenarioOptions.VehicleCount",500, ...
                    "scenarioOptions.RoadLength",200, ...
                    "scenarioOptions.MeanVehicleSpeed",20, ...
                    "scenarioOptions.VehicleSpeedStandardDeviation",0, ...
                    "scenarioOptions.ExitProbability",1, ...
                    "scenarioOptions.MergeDistance",40});

            scenario = simValues.world.TrafficScenario;
            testCase.verifyClass( ...
                scenario, ...
                "v2xsim.vehicle.scenarios.ExitRampHighwayScenario");
            testCase.verifyEqual(positionManagement.Xmin,0);
            testCase.verifyEqual(positionManagement.Xmax,200);
            testCase.verifyEqual(positionManagement.Ymin,-103.75);
            testCase.verifyEqual(positionManagement.Ymax,103.75);
            testCase.verifyTrue(any(imag( ...
                positionManagement.direction)~=0));
            testCase.verifyProjection(simValues,positionManagement);
        end

        function testAppendsLegacyManagedRsus(testCase)
            appParams = struct( ...
                nRSUs=2, ...
                RSU_xLocation=[100,200], ...
                RSU_yLocation=[20,30]);
            [~,simValues,positionManagement] = ...
                testCase.initializeScenario( ...
                    "BidirectionalHighwayScenario",{ ...
                    "scenarioOptions.VehicleCount",10},appParams);

            world = simValues.world;
            testCase.verifyEqual( ...
                height(world.TrafficScenario.VehicleKinematics),10);
            testCase.verifyEqual( ...
                world.VehicleIds,"V" + string((1:10).'));
            testCase.verifyEqual(world.RsuIds,["RSU1";"RSU2"]);
            testCase.verifyEqual( ...
                world.UeIds,[world.VehicleIds;world.RsuIds]);
            testCase.verifyEmpty(intersect(world.VehicleIds,world.RsuIds));
            testCase.verifyEqual( ...
                numel(unique(world.UeIds)),numel(world.UeIds));
            testCase.verifyEqual(simValues.IDvehicle,(1:12).');
            testCase.verifyEqual(simValues.maxID,12);
            rsuIDs = testCase.ueIndices(world,world.RsuIds);
            testCase.verifyEqual( ...
                positionManagement.XvehicleReal(rsuIDs),[100;200]);
            testCase.verifyEqual( ...
                positionManagement.YvehicleReal(rsuIDs),[20;30]);
            testCase.verifyEqual(positionManagement.v(rsuIDs),[0;0]);
            testCase.verifyEqual( ...
                positionManagement.direction(rsuIDs),[0;0]);
            testCase.verifyEqual( ...
                positionManagement.XVehicle, ...
                positionManagement.XvehicleReal);
            testCase.verifyEqual( ...
                positionManagement.YVehicle, ...
                positionManagement.YvehicleReal);
        end

        function testPreservesAsynchronousVehicleSelection(testCase)
            [simParams,~] = testCase.createSimulationParameters( ...
                "BidirectionalHighwayScenario",{ ...
                    "scenarioOptions.VehicleCount",20});
            simParams.technology = constants.TECH_ONLY_CV2X;
            simParams.BRAlgorithm = constants.REASSIGN_BR_STD_MODE_4;
            simParams.asynMode = 1;
            simParams.percAsynUser = 0.25;
            appParams = struct( ...
                nRSUs=2, ...
                RSU_xLocation=[100,200], ...
                RSU_yLocation=[20,30]);

            [simParams,simValues] = ...
                initVehiclePositions(simParams,appParams);

            testCase.verifyNumElements(simParams.IDvehicleAsyn,5);
            vehicleIDs = testCase.ueIndices( ...
                simValues.world,simValues.world.VehicleIds);
            rsuIDs = testCase.ueIndices( ...
                simValues.world,simValues.world.RsuIds);
            testCase.verifyTrue(all(ismember( ...
                simParams.IDvehicleAsyn,vehicleIDs)));
            testCase.verifyFalse(any(ismember( ...
                simParams.IDvehicleAsyn,rsuIDs)));
            testCase.verifyEqual( ...
                simParams.IDvehicleAsyn,sort(simParams.IDvehicleAsyn));
        end

        function testPositionErrorsDoNotMoveRsus(testCase)
            randomState = rng;
            testCase.addTeardown(@() rng(randomState));
            appParams = struct( ...
                nRSUs=2, ...
                RSU_xLocation=[100,200], ...
                RSU_yLocation=[20,30]);
            [~,simValues,positionManagement] = ...
                testCase.initializeScenario( ...
                    "BrownianMotionScenario",{ ...
                    "scenarioOptions.VehicleCount",10, ...
                    "positionErrorModules","Gaussian", ...
                    "positionErrorOptions.Gaussian." + ...
                        "StandardDeviationMeters",10}, ...
                    appParams);

            world = simValues.world;
            vehicleIDs = testCase.ueIndices(world,world.VehicleIds);
            rsuIDs = testCase.ueIndices(world,world.RsuIds);
            actualPositions = [ ...
                positionManagement.XvehicleReal, ...
                positionManagement.YvehicleReal];
            apparentPositions = [ ...
                simValues.XvehicleEstimated, ...
                simValues.YvehicleEstimated];

            testCase.verifyTrue(any(any( ...
                apparentPositions(vehicleIDs,:) ~= ...
                actualPositions(vehicleIDs,:))));
            testCase.verifyEqual( ...
                apparentPositions(rsuIDs,:),actualPositions(rsuIDs,:));
        end

        function testConfiguredDelayRetainsPositionHistory(testCase)
            [simParams,simValues,positionManagement] = ...
                testCase.initializeScenario( ...
                    "BrownianMotionScenario",{ ...
                    "simulationTime",2, ...
                    "positionTimeResolution",0.5, ...
                    "scenarioOptions.VehicleCount",5, ...
                    "scenarioOptions.MeanVehicleSpeed",20, ...
                    "scenarioOptions.VehicleSpeedStandardDeviation",0, ...
                    "positionErrorModules","Delay", ...
                    "positionErrorOptions.Delay.DelaySeconds",1});
            initialPositions = [ ...
                simValues.XvehicleEstimated, ...
                simValues.YvehicleEstimated];

            [positionManagement,simValues] = ...
                testCase.advanceObservedPositions( ...
                    simParams,simValues,positionManagement,0.5);
            halfSecondPositions = [ ...
                positionManagement.XvehicleReal, ...
                positionManagement.YvehicleReal];
            testCase.verifyEqual( ...
                [simValues.XvehicleEstimated, ...
                simValues.YvehicleEstimated],initialPositions);

            [positionManagement,simValues] = ...
                testCase.advanceObservedPositions( ...
                    simParams,simValues,positionManagement,1);
            testCase.verifyEqual( ...
                [simValues.XvehicleEstimated, ...
                simValues.YvehicleEstimated],initialPositions);

            [~,simValues] = testCase.advanceObservedPositions( ...
                simParams,simValues,positionManagement,1.5);
            testCase.verifyEqual( ...
                [simValues.XvehicleEstimated, ...
                simValues.YvehicleEstimated],halfSecondPositions);
        end

        function testConfiguredFalseExitReceivesRampContext(testCase)
            [~,simValues,positionManagement] = ...
                testCase.initializeScenario( ...
                    "ExitRampHighwayScenario",{ ...
                    "scenarioOptions.VehicleCount",500, ...
                    "scenarioOptions.RoadLength",200, ...
                    "scenarioOptions.MeanVehicleSpeed",20, ...
                    "scenarioOptions.VehicleSpeedStandardDeviation",0, ...
                    "scenarioOptions.ExitProbability",0, ...
                    "scenarioOptions.MergeDistance",40, ...
                    "positionErrorModules","FalseExit", ...
                    "positionErrorOptions.FalseExit." + ...
                        "CurseProbability",1});

            routeStates = ...
                simValues.world.TrafficScenario.VehicleRouteStates;
            affected = routeStates.Route == "Merge" | ...
                routeStates.Route == "Adjacent";
            vehicleIDs = testCase.ueIndices( ...
                simValues.world,simValues.world.VehicleIds);
            actualPositions = [ ...
                positionManagement.XvehicleReal(vehicleIDs), ...
                positionManagement.YvehicleReal(vehicleIDs)];
            apparentPositions = [ ...
                simValues.XvehicleEstimated(vehicleIDs), ...
                simValues.YvehicleEstimated(vehicleIDs)];

            testCase.verifyTrue(any(affected));
            testCase.verifyTrue(any(any( ...
                apparentPositions(affected,:) ~= ...
                actualPositions(affected,:))));
            testCase.verifyEqual( ...
                apparentPositions(~affected,:), ...
                actualPositions(~affected,:));
        end

        function testConfiguredFalseExitFollowsRampTrajectory(testCase)
            [simParams,simValues,positionManagement] = ...
                testCase.initializeScenario( ...
                    "ExitRampHighwayScenario",{ ...
                    "simulationTime",10, ...
                    "positionTimeResolution",0.1, ...
                    "scenarioOptions.VehicleCount",500, ...
                    "scenarioOptions.RoadLength",200, ...
                    "scenarioOptions.MeanVehicleSpeed",20, ...
                    "scenarioOptions.VehicleSpeedStandardDeviation",0, ...
                    "scenarioOptions.RerollSpeedOnWrapAround",false, ...
                    "scenarioOptions.ExitProbability",0, ...
                    "scenarioOptions.MergeDistance",40, ...
                    "positionErrorModules","FalseExit", ...
                    "positionErrorOptions.FalseExit." + ...
                        "CurseProbability",1});
            routeStates = ...
                simValues.world.TrafficScenario.VehicleRouteStates;
            vehicleIndex = find(routeStates.Route == "Outer",1);
            testCase.assertNotEmpty(vehicleIndex);
            vehicleName = routeStates.Properties.RowNames{vehicleIndex};
            vehicleID = testCase.ueIndices( ...
                simValues.world,string(vehicleName));

            currentTime = 0;
            while simValues.world.TrafficScenario. ...
                    VehicleRouteStates.Route( ...
                    vehicleName) == "Outer"
                currentTime = currentTime + ...
                    simParams.positionTimeResolution;
                [positionManagement,simValues] = ...
                    testCase.advanceObservedPositions( ...
                        simParams,simValues, ...
                        positionManagement,currentTime);
                testCase.assertLessThan(currentTime,6);
            end

            sampleCount = 10;
            actualTrajectory = zeros(sampleCount,2);
            apparentTrajectory = zeros(sampleCount,2);
            expectedRampTrajectory = zeros(sampleCount,2);
            rampProgress = zeros(sampleCount,1);
            for sampleIndex = 1:sampleCount
                scenario = simValues.world.TrafficScenario;
                routeState = ...
                    scenario.VehicleRouteStates(vehicleName,:);
                testCase.verifyTrue(ismember( ...
                    routeState.Route,["Merge","Adjacent"]));

                actualPosition = ...
                    scenario.VehicleKinematics(vehicleName,["X","Y"]);
                actualTrajectory(sampleIndex,:) = [ ...
                    actualPosition.X,actualPosition.Y];
                geometry = scenario.Geometry;
                distancePastFork = routeState.TravelDirection .* ...
                    (actualPosition.X - geometry.ForkX);
                rampProgress(sampleIndex) = ...
                    distancePastFork ./ (geometry.RoadLength ./ 2);
                expectedRampTrajectory(sampleIndex,:) = ...
                    scenario.LaneNetwork.evaluate( ...
                        geometry.getRampLaneId( ...
                            routeState.TravelDirection), ...
                        rampProgress(sampleIndex));
                apparentTrajectory(sampleIndex,:) = [ ...
                    simValues.XvehicleEstimated(vehicleID), ...
                    simValues.YvehicleEstimated(vehicleID)];

                currentTime = currentTime + ...
                    simParams.positionTimeResolution;
                [positionManagement,simValues] = ...
                    testCase.advanceObservedPositions( ...
                        simParams,simValues, ...
                        positionManagement,currentTime);
            end

            testCase.verifyEqual( ...
                apparentTrajectory,expectedRampTrajectory, ...
                AbsTol=1e-12);
            testCase.verifyNotEqual( ...
                apparentTrajectory,actualTrajectory);
            testCase.verifyGreaterThan(diff(rampProgress),0);
        end

        function testConfiguredFalseMergeFollowsMainlineTrajectory( ...
                testCase)
            [simParams,simValues,positionManagement] = ...
                testCase.initializeScenario( ...
                    "ExitRampHighwayScenario",{ ...
                    "simulationTime",10, ...
                    "positionTimeResolution",0.1, ...
                    "scenarioOptions.VehicleCount",500, ...
                    "scenarioOptions.RoadLength",200, ...
                    "scenarioOptions.MeanVehicleSpeed",20, ...
                    "scenarioOptions.VehicleSpeedStandardDeviation",0, ...
                    "scenarioOptions.RerollSpeedOnWrapAround",false, ...
                    "scenarioOptions.ExitProbability",1, ...
                    "scenarioOptions.MergeDistance",20, ...
                    "positionErrorModules","FalseMerge", ...
                    "positionErrorOptions.FalseMerge." + ...
                        "CurseProbability",1});
            routeStates = ...
                simValues.world.TrafficScenario.VehicleRouteStates;
            vehicleIndex = find(routeStates.Route == "Outer",1);
            testCase.assertNotEmpty(vehicleIndex);
            vehicleName = routeStates.Properties.RowNames{vehicleIndex};
            vehicleID = testCase.ueIndices( ...
                simValues.world,string(vehicleName));

            currentTime = 0;
            while simValues.world.TrafficScenario. ...
                    VehicleRouteStates.Route( ...
                    vehicleName) == "Outer"
                currentTime = currentTime + ...
                    simParams.positionTimeResolution;
                [positionManagement,simValues] = ...
                    testCase.advanceObservedPositions( ...
                        simParams,simValues, ...
                        positionManagement,currentTime);
                testCase.assertLessThan(currentTime,6);
            end

            sampleCount = 20;
            actualTrajectory = zeros(sampleCount,2);
            apparentTrajectory = zeros(sampleCount,2);
            expectedMainlineTrajectory = zeros(sampleCount,2);
            distancePastFork = zeros(sampleCount,1);
            onMergeConnector = false(sampleCount,1);
            for sampleIndex = 1:sampleCount
                scenario = simValues.world.TrafficScenario;
                routeState = ...
                    scenario.VehicleRouteStates(vehicleName,:);
                testCase.verifyEqual(routeState.Route,"Ramp");

                actualPosition = ...
                    scenario.VehicleKinematics(vehicleName,["X","Y"]);
                actualTrajectory(sampleIndex,:) = [ ...
                    actualPosition.X,actualPosition.Y];
                geometry = scenario.Geometry;
                distancePastFork(sampleIndex) = ...
                    routeState.TravelDirection .* ...
                    (actualPosition.X - geometry.ForkX);
                onMergeConnector(sampleIndex) = ...
                    distancePastFork(sampleIndex) <= ...
                    geometry.MergeDistance;

                if onMergeConnector(sampleIndex)
                    expectedMainlineTrajectory(sampleIndex,:) = ...
                        scenario.LaneNetwork.evaluate( ...
                            geometry.getMergeLaneId( ...
                                routeState.TravelDirection), ...
                            distancePastFork(sampleIndex) ./ ...
                                geometry.MergeDistance);
                else
                    laneID = geometry.getMainlineLaneId( ...
                        routeState.TravelDirection, ...
                        geometry.NLanes - 1);
                    progress = actualPosition.X ./ ...
                        geometry.RoadLength;
                    if routeState.TravelDirection < 0
                        progress = 1 - progress;
                    end
                    expectedMainlineTrajectory(sampleIndex,:) = ...
                        scenario.LaneNetwork.evaluate( ...
                            laneID,progress);
                end
                apparentTrajectory(sampleIndex,:) = [ ...
                    simValues.XvehicleEstimated(vehicleID), ...
                    simValues.YvehicleEstimated(vehicleID)];

                currentTime = currentTime + ...
                    simParams.positionTimeResolution;
                [positionManagement,simValues] = ...
                    testCase.advanceObservedPositions( ...
                        simParams,simValues, ...
                        positionManagement,currentTime);
            end

            testCase.verifyTrue(any(onMergeConnector));
            testCase.verifyTrue(any(~onMergeConnector));
            testCase.verifyEqual( ...
                apparentTrajectory,expectedMainlineTrajectory, ...
                AbsTol=1e-12);
            testCase.verifyNotEqual( ...
                apparentTrajectory,actualTrajectory);
            testCase.verifyGreaterThan(diff(distancePastFork),0);
        end
    end

    methods (Access = private)
        function [simParams,simValues,positionManagement,appParams] = ...
                initializeScenario( ...
                testCase,typeOfScenario,scenarioArguments,appParams)
            if nargin<4
                appParams = struct(nRSUs=0);
            end
            [simParams,remainingArguments] = ...
                testCase.createSimulationParameters( ...
                    typeOfScenario,scenarioArguments);
            testCase.assertEmpty(remainingArguments{1});
            simParams.technology = constants.TECH_ONLY_11P;

            [simParams,simValues,positionManagement,appParams] = ...
                initVehiclePositions(simParams,appParams);
        end

        function [simParams,remainingArguments] = ...
                createSimulationParameters( ...
                ~,typeOfScenario,scenarioArguments)
            inputArguments = [ ...
                {"seed",1,"typeOfScenario",typeOfScenario}, ...
                scenarioArguments];
            [simParams,remainingArguments] = ...
                initiateMainSimulationParameters("",inputArguments);
        end

        function [positionManagement,simValues] = ...
                advanceObservedPositions( ...
                ~,simParams,simValues,positionManagement,currentTime)
            [~,~,~,~,positionManagement,simValues] = updatePosition( ...
                currentTime,simValues.IDvehicle, ...
                simParams.positionTimeResolution, ...
                positionManagement,simValues, ...
                struct(printSpeed=false),simParams);

            simValues.XvehicleEstimatedLegacy = ...
                positionManagement.XvehicleReal;
            simValues.YvehicleEstimatedLegacy = ...
                positionManagement.YvehicleReal;
            simValues.XvehicleEstimated = ...
                simValues.XvehicleEstimatedLegacy;
            simValues.YvehicleEstimated = ...
                simValues.YvehicleEstimatedLegacy;
            simValues = applyPositionErrorChain( ...
                simParams,simValues,currentTime);
        end

        function verifyProjection(testCase,simValues,positionManagement)
            world = simValues.world;
            testCase.verifyWorldIdentity(world);
            vehicleKinematics = world.TrafficScenario. ...
                VehicleKinematics(cellstr(world.VehicleIds),:);
            vehicleIDs = testCase.ueIndices(world,world.VehicleIds);
            rsuIDs = testCase.ueIndices(world,world.RsuIds);
            uePositions = world.UePositions;

            testCase.verifyClass(positionManagement.XvehicleReal,"double");
            testCase.verifySize( ...
                positionManagement.XvehicleReal, ...
                [numel(world.UeIds),1]);
            testCase.verifyEqual( ...
                positionManagement.XvehicleReal,uePositions.X);
            testCase.verifyEqual( ...
                positionManagement.YvehicleReal,uePositions.Y);

            expectedSpeed = hypot(vehicleKinematics.vX,vehicleKinematics.vY);
            expectedDirection = complex(zeros(height(vehicleKinematics),1));
            movingVehicles = expectedSpeed>0;
            expectedDirection(movingVehicles) = complex( ...
                vehicleKinematics.vX(movingVehicles)./ ...
                    expectedSpeed(movingVehicles), ...
                vehicleKinematics.vY(movingVehicles)./ ...
                    expectedSpeed(movingVehicles));
            testCase.verifyEqual( ...
                positionManagement.v(vehicleIDs),expectedSpeed);
            testCase.verifyEqual( ...
                positionManagement.direction(vehicleIDs), ...
                expectedDirection,AbsTol=1e-14);
            testCase.verifyEqual( ...
                positionManagement.v(rsuIDs),zeros(numel(rsuIDs),1));
            testCase.verifyEqual( ...
                positionManagement.direction(rsuIDs), ...
                zeros(numel(rsuIDs),1));
            testCase.verifyEqual( ...
                positionManagement.XVehicle, ...
                positionManagement.XvehicleReal);
            testCase.verifyEqual( ...
                positionManagement.YVehicle, ...
                positionManagement.YvehicleReal);
        end

        function verifyWorldIdentity(testCase,world)
            testCase.verifyEqual( ...
                world.UeIds,[world.VehicleIds;world.RsuIds]);
            testCase.verifyEmpty(intersect(world.VehicleIds,world.RsuIds));
            testCase.verifyEqual( ...
                numel(unique(world.UeIds)),numel(world.UeIds));
        end

        function indices = ueIndices(testCase,world,ueIds)
            [isPresent,indices] = ismember(string(ueIds),world.UeIds);
            testCase.assertTrue(all(isPresent));
            indices = indices(:);
        end
    end
end
