classdef InitVehiclePositionsTest < matlab.unittest.TestCase
    %INITVEHICLEPOSITIONSTEST Tests Scenario-to-legacy initialization.

    methods (TestClassSetup)
        function addCompatibilityPaths(testCase)
            projectRoot = fileparts(fileparts(fileparts(fileparts( ...
                mfilename("fullpath")))));
            pathsToAdd = [ ...
                fullfile(projectRoot,"old_src","MatFilesInit"), ...
                fullfile(projectRoot,"old_src","MatFilesPosition")];
            for pathToAdd = pathsToAdd
                addpath(pathToAdd);
                testCase.addTeardown(@() rmpath(pathToAdd));
            end
        end
    end

    methods (Test)
        function testInitializesBrownianScenario(testCase)
            [~,simValues,positionManagement] = ...
                testCase.initializeScenario( ...
                    "BrownianMotionScenario",{ ...
                    "scenarioOptions.VehicleCount",25, ...
                    "scenarioOptions.SimulationAreaSize",500, ...
                    "scenarioOptions.MeanVehicleSpeed",40, ...
                    "scenarioOptions.VehicleSpeedStandardDeviation",5});

            testCase.verifyClass( ...
                simValues.scenario, ...
                "v2xsim.vehicle.scenarios.BrownianMotionScenario");
            testCase.verifyEqual( ...
                simValues.scenario.SimulationAreaSize,500);
            testCase.verifyEqual(positionManagement.Xmin,0);
            testCase.verifyEqual(positionManagement.Xmax,500);
            testCase.verifyEqual(positionManagement.Ymin,0);
            testCase.verifyEqual(positionManagement.Ymax,500);
            testCase.verifyProjection(simValues,positionManagement);
        end

        function testInitializesBidirectionalHighwayScenario(testCase)
            [~,simValues,positionManagement] = ...
                testCase.initializeScenario( ...
                    "BidirectionalHighwayScenario",{ ...
                    "scenarioOptions.VehicleCount",30, ...
                    "scenarioOptions.NLanes",3, ...
                    "scenarioOptions.LaneWidth",4, ...
                    "scenarioOptions.RoadLength",800, ...
                    "scenarioOptions.CentralDividerWidth",2, ...
                    "scenarioOptions.MeanVehicleSpeed",20, ...
                    "scenarioOptions.VehicleSpeedStandardDeviation",0, ...
                    "scenarioOptions.RerollSpeedOnWrapAround",false});

            scenario = simValues.scenario;
            testCase.verifyClass( ...
                scenario, ...
                "v2xsim.vehicle.scenarios.BidirectionalHighwayScenario");
            testCase.verifyEqual(scenario.NLanes,3);
            testCase.verifyEqual(scenario.LaneWidth,4);
            testCase.verifyEqual(scenario.RoadLength,800);
            testCase.verifyEqual(positionManagement.Xmin,0);
            testCase.verifyEqual(positionManagement.Xmax,800);
            testCase.verifyEqual(positionManagement.Ymin,-11);
            testCase.verifyEqual(positionManagement.Ymax,11);
            testCase.verifyProjection(simValues,positionManagement);
        end

        function testInitializesEtsiHighwayScenario(testCase)
            [~,simValues,positionManagement] = ...
                testCase.initializeScenario( ...
                    "EtsiHighwayScenario",{ ...
                    "scenarioOptions.TrafficModel", ...
                        "LowSpeedHighDensity", ...
                    "scenarioOptions.Placement","Gaussian", ...
                    "scenarioOptions.MinimumRoadLength",2500});

            import v2xsim.vehicle.scenarios.etsihighway.Placement
            import v2xsim.vehicle.scenarios.etsihighway.TrafficModel

            scenario = simValues.scenario;
            testCase.verifyClass( ...
                scenario,"v2xsim.vehicle.scenarios.EtsiHighwayScenario");
            testCase.verifyEqual( ...
                scenario.TrafficModel,TrafficModel.LowSpeedHighDensity);
            testCase.verifyEqual(scenario.Placement,Placement.Gaussian);
            testCase.verifyGreaterThanOrEqual(scenario.RoadLength,2500);
            testCase.verifyEqual(positionManagement.Xmax,scenario.RoadLength);
            testCase.verifyEqual(positionManagement.Ymin,-10);
            testCase.verifyEqual(positionManagement.Ymax,10);
            testCase.verifyProjection(simValues,positionManagement);
        end

        function testInitializesExitRampScenario(testCase)
            [~,simValues,positionManagement] = ...
                testCase.initializeScenario( ...
                    "ExitRampHighwayScenario",{ ...
                    "scenarioOptions.VehicleCount",500, ...
                    "scenarioOptions.RoadLength",200, ...
                    "scenarioOptions.MeanVehicleSpeed",20, ...
                    "scenarioOptions.VehicleSpeedStandardDeviation",0, ...
                    "scenarioOptions.ExitProbability",1, ...
                    "scenarioOptions.MergeDistance",40});

            scenario = simValues.scenario;
            testCase.verifyClass( ...
                scenario, ...
                "v2xsim.vehicle.scenarios.ExitRampHighwayScenario");
            testCase.verifyEqual(positionManagement.Xmin,0);
            testCase.verifyEqual(positionManagement.Xmax,200);
            testCase.verifyEqual(positionManagement.Ymin,-103.75);
            testCase.verifyEqual(positionManagement.Ymax,103.75);
            testCase.verifyTrue(any(imag( ...
                positionManagement.direction)~=0));
            testCase.verifyProjection(simValues,positionManagement);
        end

        function testAppendsLegacyManagedRsus(testCase)
            appParams = struct( ...
                nRSUs=2, ...
                RSU_xLocation=[100,200], ...
                RSU_yLocation=[20,30]);
            [~,simValues,positionManagement] = ...
                testCase.initializeScenario( ...
                    "BidirectionalHighwayScenario",{ ...
                    "scenarioOptions.VehicleCount",10},appParams);

            testCase.verifyEqual(height(simValues.scenario.VehicleKinematics),10);
            testCase.verifyEqual(simValues.scenarioVehicleIDs,(1:10).');
            testCase.verifyEqual(simValues.IDvehicle,(1:12).');
            testCase.verifyEqual(simValues.maxID,12);
            testCase.verifyEqual( ...
                positionManagement.XvehicleReal(end-1:end),[100;200]);
            testCase.verifyEqual( ...
                positionManagement.YvehicleReal(end-1:end),[20;30]);
            testCase.verifyEqual(positionManagement.v(end-1:end),[0;0]);
            testCase.verifyEqual( ...
                positionManagement.direction(end-1:end),[0;0]);
            testCase.verifyEqual( ...
                positionManagement.XVehicle, ...
                positionManagement.XvehicleReal);
            testCase.verifyEqual( ...
                positionManagement.YVehicle, ...
                positionManagement.YvehicleReal);
        end

        function testPreservesAsynchronousVehicleSelection(testCase)
            [simParams,~] = testCase.createSimulationParameters( ...
                "BidirectionalHighwayScenario",{ ...
                "scenarioOptions.VehicleCount",20});
            simParams.technology = constants.TECH_ONLY_CV2X;
            simParams.BRAlgorithm = constants.REASSIGN_BR_STD_MODE_4;
            simParams.asynMode = 1;
            simParams.percAsynUser = 0.25;
            appParams = struct(nRSUs=0);

            [simParams,simValues] = ...
                initVehiclePositions(simParams,appParams);

            testCase.verifyNumElements(simParams.IDvehicleAsyn,5);
            testCase.verifyTrue(all(ismember( ...
                simParams.IDvehicleAsyn,simValues.scenarioVehicleIDs)));
            testCase.verifyEqual( ...
                simParams.IDvehicleAsyn,sort(simParams.IDvehicleAsyn));
        end
    end

    methods (Access = private)
        function [simParams,simValues,positionManagement,appParams] = ...
                initializeScenario( ...
                testCase,typeOfScenario,scenarioArguments,appParams)
            if nargin<4
                appParams = struct(nRSUs=0);
            end
            [simParams,remainingArguments] = ...
                testCase.createSimulationParameters( ...
                    typeOfScenario,scenarioArguments);
            testCase.assertEmpty(remainingArguments{1});
            simParams.technology = constants.TECH_ONLY_11P;

            [simParams,simValues,positionManagement,appParams] = ...
                initVehiclePositions(simParams,appParams);
        end

        function [simParams,remainingArguments] = ...
                createSimulationParameters( ...
                ~,typeOfScenario,scenarioArguments)
            inputArguments = [ ...
                {"seed",1,"typeOfScenario",typeOfScenario}, ...
                scenarioArguments];
            [simParams,remainingArguments] = ...
                initiateMainSimulationParameters("",inputArguments);
        end

        function verifyProjection(testCase,simValues,positionManagement)
            rowNames = simValues.scenarioVehicleRowNames;
            vehicleKinematics = ...
                simValues.scenario.VehicleKinematics(rowNames,:);
            scenarioVehicleIDs = simValues.scenarioVehicleIDs;

            testCase.verifyClass(positionManagement.XvehicleReal,"double");
            testCase.verifySize( ...
                positionManagement.XvehicleReal, ...
                [height(vehicleKinematics),1]);
            testCase.verifyEqual( ...
                positionManagement.XvehicleReal(scenarioVehicleIDs), ...
                vehicleKinematics.X);
            testCase.verifyEqual( ...
                positionManagement.YvehicleReal(scenarioVehicleIDs), ...
                vehicleKinematics.Y);

            expectedSpeed = hypot(vehicleKinematics.vX,vehicleKinematics.vY);
            expectedDirection = complex(zeros(height(vehicleKinematics),1));
            movingVehicles = expectedSpeed>0;
            expectedDirection(movingVehicles) = complex( ...
                vehicleKinematics.vX(movingVehicles)./ ...
                    expectedSpeed(movingVehicles), ...
                vehicleKinematics.vY(movingVehicles)./ ...
                    expectedSpeed(movingVehicles));
            testCase.verifyEqual( ...
                positionManagement.v(scenarioVehicleIDs),expectedSpeed);
            testCase.verifyEqual( ...
                positionManagement.direction(scenarioVehicleIDs), ...
                expectedDirection,AbsTol=1e-14);
            testCase.verifyEqual( ...
                positionManagement.XVehicle, ...
                positionManagement.XvehicleReal);
            testCase.verifyEqual( ...
                positionManagement.YVehicle, ...
                positionManagement.YvehicleReal);
        end
    end
end
