classdef InitiateMainSimulationParametersTest < matlab.unittest.TestCase
    %INITIATEMAINSIMULATIONPARAMETERSTEST Tests scenario config bridging.

    methods (TestClassSetup)
        function addLegacyInitializationPath(testCase)
            projectRoot = fileparts(fileparts(fileparts(fileparts( ...
                mfilename("fullpath")))));
            legacyInitializationPath = fullfile( ...
                projectRoot, "old_src", "MatFilesInit");
            addpath(legacyInitializationPath);
            testCase.addTeardown(@() rmpath(legacyInitializationPath));
        end
    end

    methods (Test)
        function testDefaultSelectsBidirectionalHighway(testCase)
            [simParams, remainingArguments] = ...
                testCase.initializeWithArguments({"seed", 1});

            testCase.verifyEqual( ...
                simParams.typeOfScenario, ...
                'BidirectionalHighwayScenario');
            testCase.verifyEqual( ...
                string(fieldnames(simParams.scenarioOptions)), ...
                ["VehicleCount"; "NLanes"; "LaneWidth"; ...
                "RoadLength"; "CentralDividerWidth"; ...
                "MeanVehicleSpeed"; ...
                "VehicleSpeedStandardDeviation"; ...
                "RerollSpeedOnWrapAround"]);
            testCase.verifyEqual(simParams.scenarioOptions.VehicleCount, 100);
            testCase.verifyEmpty(remainingArguments{1});
        end

        function testBrownianOptionsUseConstructorNames(testCase)
            inputArguments = { ...
                "seed", 1, ...
                "typeOfScenario", "BrownianMotionScenario", ...
                "scenarioOptions.VehicleCount", 25, ...
                "scenarioOptions.SimulationAreaSize", 500, ...
                "scenarioOptions.MeanVehicleSpeed", 40, ...
                "scenarioOptions.VehicleSpeedStandardDeviation", 5};

            [simParams, remainingArguments] = ...
                testCase.initializeWithArguments(inputArguments);

            testCase.verifyEqual( ...
                string(fieldnames(simParams.scenarioOptions)), ...
                ["VehicleCount"; "SimulationAreaSize"; ...
                "MeanVehicleSpeed"; ...
                "VehicleSpeedStandardDeviation"]);
            testCase.verifyEqual(simParams.scenarioOptions.VehicleCount, 25);
            testCase.verifyEqual( ...
                simParams.scenarioOptions.SimulationAreaSize, 500);
            testCase.verifyEmpty(remainingArguments{1});
        end

        function testEtsiStringsBecomeScenarioEnums(testCase)
            inputArguments = { ...
                "seed", 1, ...
                "typeOfScenario", "EtsiHighwayScenario", ...
                "scenarioOptions.TrafficModel", ...
                    "MediumSpeedMediumDensity", ...
                "scenarioOptions.Placement", "Gaussian", ...
                "scenarioOptions.MinimumRoadLength", 2500};

            [simParams, remainingArguments] = ...
                testCase.initializeWithArguments(inputArguments);

            import v2xsim.vehicle.scenarios.etsihighway.Placement
            import v2xsim.vehicle.scenarios.etsihighway.TrafficModel

            testCase.verifyEqual( ...
                simParams.scenarioOptions.TrafficModel, ...
                TrafficModel.MediumSpeedMediumDensity);
            testCase.verifyEqual( ...
                simParams.scenarioOptions.Placement, Placement.Gaussian);
            testCase.verifyEqual( ...
                simParams.scenarioOptions.MinimumRoadLength, 2500);
            testCase.verifyEmpty(remainingArguments{1});
        end

        function testExitRampOptionsUseConstructorNames(testCase)
            inputArguments = { ...
                "seed", 1, ...
                "typeOfScenario", "ExitRampHighwayScenario", ...
                "scenarioOptions.VehicleCount", 80, ...
                "scenarioOptions.NLanes", 3, ...
                "scenarioOptions.ExitProbability", 0.2, ...
                "scenarioOptions.MergeDistance", 60};

            [simParams, remainingArguments] = ...
                testCase.initializeWithArguments(inputArguments);

            testCase.verifyEqual( ...
                string(fieldnames(simParams.scenarioOptions)), ...
                ["VehicleCount"; "NLanes"; "LaneWidth"; ...
                "RoadLength"; "CentralDividerWidth"; ...
                "MeanVehicleSpeed"; ...
                "VehicleSpeedStandardDeviation"; ...
                "RerollSpeedOnWrapAround"; "ExitProbability"; ...
                "MergeDistance"]);
            testCase.verifyEqual(simParams.scenarioOptions.NLanes, 3);
            testCase.verifyEqual( ...
                simParams.scenarioOptions.ExitProbability, 0.2);
            testCase.verifyEqual( ...
                simParams.scenarioOptions.MergeDistance, 60);
            testCase.verifyEmpty(remainingArguments{1});
        end

        function testConfigFileAndCommandLinePrecedence(testCase)
            configPath = string(tempname) + ".cfg";
            writelines([ ...
                "[seed] 1", ...
                "[typeOfScenario] BrownianMotionScenario", ...
                "[scenarioOptions.VehicleCount] 20", ...
                "[scenarioOptions.SimulationAreaSize] 750", ...
                "[scenarioOptions.MeanVehicleSpeed] 30"], configPath);
            testCase.addTeardown(@() delete(configPath));

            inputArguments = { ...
                "scenarioOptions.VehicleCount", 35, ...
                "scenarioOptions.VehicleSpeedStandardDeviation", 2};
            [simParams, remainingArguments] = ...
                testCase.initializeWithArguments( ...
                    inputArguments, configPath);

            testCase.verifyEqual(simParams.scenarioOptions.VehicleCount, 35);
            testCase.verifyEqual( ...
                simParams.scenarioOptions.SimulationAreaSize, 750);
            testCase.verifyEqual( ...
                simParams.scenarioOptions.MeanVehicleSpeed, 30);
            testCase.verifyEqual( ...
                simParams.scenarioOptions.VehicleSpeedStandardDeviation, 2);
            testCase.verifyEmpty(remainingArguments{1});
        end

        function testRemovedLegacyScenarioNameIsRejected(testCase)
            testCase.verifyError( ...
                @() testCase.initializeWithArguments( ...
                    {"seed", 1, "typeOfScenario", "PPP"}), ...
                "v2xsim:legacy:UnknownScenario");
        end
    end

    methods (Access = private)
        function [simParams, remainingArguments] = ...
                initializeWithArguments(~, inputArguments, configPath)
            if nargin < 3
                configPath = "";
            end

            [simParams, remainingArguments] = ...
                initiateMainSimulationParameters( ...
                    configPath, inputArguments);
        end
    end
end
