classdef UpdatePositionTest < matlab.unittest.TestCase
    %UPDATEPOSITIONTEST Tests Scenario-to-legacy position updates.

    methods (TestClassSetup)
        function addCompatibilityPaths(testCase)
            projectRoot = fileparts(fileparts(fileparts(fileparts( ...
                mfilename("fullpath")))));
            pathsToAdd = [ ...
                fullfile(projectRoot,"old_src","MatFilesInit"), ...
                fullfile(projectRoot,"old_src","MatFilesPosition")];
            for pathToAdd = pathsToAdd
                addpath(pathToAdd);
                testCase.addTeardown(@() rmpath(pathToAdd));
            end
        end
    end

    methods (Test)
        function testUpdatesEveryCurrentScenarioThroughOnePath(testCase)
            configurations = { ...
                "BrownianMotionScenario",{ ...
                    "scenarioOptions.VehicleCount",12, ...
                    "scenarioOptions.SimulationAreaSize",500}; ...
                "BidirectionalHighwayScenario",{ ...
                    "scenarioOptions.VehicleCount",12, ...
                    "scenarioOptions.RerollSpeedOnWrapAround",false}; ...
                "EtsiHighwayScenario",{ ...
                    "scenarioOptions.TrafficModel", ...
                        "HighSpeedLowDensity"}; ...
                "ExitRampHighwayScenario",{ ...
                    "scenarioOptions.VehicleCount",12, ...
                    "scenarioOptions.ExitProbability",0, ...
                    "scenarioOptions.RerollSpeedOnWrapAround",false}};

            for configurationIndex = 1:size(configurations,1)
                scenarioName = configurations{configurationIndex,1};
                scenarioArguments = configurations{configurationIndex,2};
                [simParams,simValues,positionManagement] = ...
                    testCase.initializeScenario( ...
                        scenarioName,scenarioArguments);
                previousKinematics = ...
                    simValues.scenario.VehicleKinematics;
                idVehicle = simValues.IDvehicle;

                [indexNew,indexOld,indexOldToOld,idExit, ...
                    positionManagement,simValues] = updatePosition( ...
                        1,idVehicle,0.1,positionManagement,simValues, ...
                        struct(printSpeed=false),simParams);

                testCase.verifyEmpty(indexNew);
                testCase.verifyEqual(indexOld,(1:numel(idVehicle)).');
                testCase.verifyEqual(indexOldToOld,indexOld);
                testCase.verifyEmpty(idExit);
                testCase.verifyNotEqual( ...
                    simValues.scenario.VehicleKinematics, ...
                    previousKinematics, ...
                    sprintf('%s did not advance.',scenarioName));
                testCase.verifyProjection(simValues,positionManagement);
            end
        end

        function testUsesRowNamesInsteadOfReturnedRowOrder(testCase)
            import v2xsim.vehicle.scenario.VehicleLifecycleTransition

            initialKinematics = testCase.kinematicsTable( ...
                [10;20],[1;2],[3;4],[0;0],["A";"B"]);
            nextKinematics = testCase.kinematicsTable( ...
                [200;100],[20;10],[20;10],[0;0],["B";"A"]);
            transition = repmat( ...
                VehicleLifecycleTransition.Unchanged,2,1);
            transitions = table( ...
                transition,VariableNames="Transition", ...
                RowNames=["B";"A"]);
            scenario = ...
                v2xsimtest.vehicle.scenario.fixture.ScenarioStub( ...
                    initialKinematics,nextKinematics,transitions);

            simValues = struct();
            simValues.scenario = scenario;
            simValues.scenarioVehicleRowNames = ...
                initialKinematics.Properties.RowNames;
            simValues.scenarioVehicleIDs = [1;2];
            simValues.maxID = 3;
            positionManagement = struct( ...
                XvehicleReal=[10;20;999], ...
                YvehicleReal=[1;2;999], ...
                v=[3;4;0], ...
                direction=[1;1;0]);

            [~,~,~,~,positionManagement,simValues] = updatePosition( ...
                1,(1:3).',0.5,positionManagement,simValues, ...
                struct(printSpeed=false),struct());

            testCase.verifyEqual( ...
                positionManagement.XvehicleReal,[100;200;999]);
            testCase.verifyEqual( ...
                positionManagement.YvehicleReal,[10;20;999]);
            testCase.verifyEqual(positionManagement.v,[10;20;0]);
            testCase.verifyEqual(positionManagement.direction,[1;1;0]);
            testCase.verifyEqual(simValues.scenario.LastDeltaTime,0.5);
        end

        function testLeavesLegacyManagedRsusUnchanged(testCase)
            appParams = struct( ...
                nRSUs=2, ...
                RSU_xLocation=[100,200], ...
                RSU_yLocation=[20,30]);
            [simParams,simValues,positionManagement] = ...
                testCase.initializeScenario( ...
                    "BidirectionalHighwayScenario",{ ...
                    "scenarioOptions.VehicleCount",10, ...
                    "scenarioOptions.RerollSpeedOnWrapAround",false}, ...
                    appParams);
            idVehicle = simValues.IDvehicle;
            rsuIDs = idVehicle(end-1:end);
            previousRsuState = [ ...
                positionManagement.XvehicleReal(rsuIDs), ...
                positionManagement.YvehicleReal(rsuIDs), ...
                positionManagement.v(rsuIDs), ...
                positionManagement.direction(rsuIDs)];

            [~,~,~,~,positionManagement,simValues] = updatePosition( ...
                1,idVehicle,0.1,positionManagement,simValues, ...
                struct(printSpeed=false),simParams);

            currentRsuState = [ ...
                positionManagement.XvehicleReal(rsuIDs), ...
                positionManagement.YvehicleReal(rsuIDs), ...
                positionManagement.v(rsuIDs), ...
                positionManagement.direction(rsuIDs)];
            testCase.verifyEqual(currentRsuState,previousRsuState);
            testCase.verifyProjection(simValues,positionManagement);
        end
    end

    methods (Access = private)
        function [simParams,simValues,positionManagement] = ...
                initializeScenario( ...
                testCase,typeOfScenario,scenarioArguments,appParams)
            if nargin<4
                appParams = struct(nRSUs=0);
            end
            inputArguments = [ ...
                {"seed",1,"typeOfScenario",typeOfScenario}, ...
                scenarioArguments];
            [simParams,remainingArguments] = ...
                initiateMainSimulationParameters("",inputArguments);
            testCase.assertEmpty(remainingArguments{1});
            simParams.technology = constants.TECH_ONLY_11P;
            [simParams,simValues,positionManagement] = ...
                initVehiclePositions(simParams,appParams);
        end

        function verifyProjection(testCase,simValues,positionManagement)
            vehicleKinematics = simValues.scenario.VehicleKinematics( ...
                simValues.scenarioVehicleRowNames,:);
            vehicleIDs = simValues.scenarioVehicleIDs;
            speed = hypot(vehicleKinematics.vX,vehicleKinematics.vY);
            direction = complex(zeros(height(vehicleKinematics),1));
            movingVehicles = speed>0;
            direction(movingVehicles) = complex( ...
                vehicleKinematics.vX(movingVehicles)./ ...
                    speed(movingVehicles), ...
                vehicleKinematics.vY(movingVehicles)./ ...
                    speed(movingVehicles));

            testCase.verifyEqual( ...
                positionManagement.XvehicleReal(vehicleIDs), ...
                vehicleKinematics.X);
            testCase.verifyEqual( ...
                positionManagement.YvehicleReal(vehicleIDs), ...
                vehicleKinematics.Y);
            testCase.verifyEqual(positionManagement.v(vehicleIDs),speed);
            testCase.verifyEqual( ...
                positionManagement.direction(vehicleIDs),direction, ...
                AbsTol=1e-14);
            testCase.verifyEqual( ...
                positionManagement.XVehicle, ...
                positionManagement.XvehicleReal);
            testCase.verifyEqual( ...
                positionManagement.YVehicle, ...
                positionManagement.YvehicleReal);
        end

        function vehicleKinematics = kinematicsTable( ...
                ~,x,y,vX,vY,rowNames)
            unknownAcceleration = NaN(numel(x),1);
            vehicleKinematics = table( ...
                x,y,vX,vY,unknownAcceleration,unknownAcceleration, ...
                VariableNames=["X","Y","vX","vY","aX","aY"], ...
                RowNames=rowNames);
        end
    end
end
