function mustBe2DPositionTable(value)
%MUSTBE2DPOSITIONTABLE Validate a named table of planar positions.
%   The table must contain exactly the single-column variables X and Y, in
%   meters, and one unique row name per vehicle. Coordinates must be
%   floating-point, real, and finite. An empty table may omit row names.

if ~istable(value)
    error( ...
        "v2xsim:positioning:MustBe2DPositionTable", ...
        "Vehicle positions must be provided as a table.");
end

expectedVariables = ["X", "Y"];
actualVariables = string(value.Properties.VariableNames);
if ~isequal(actualVariables, expectedVariables)
    error( ...
        "v2xsim:positioning:MustBe2DPositionTable", ...
        "The position table must contain exactly the variables X and Y, " + ...
        "in that order.");
end

for variableName = expectedVariables
    variable = value.(variableName);
    if ~(isa(variable, "single") || isa(variable, "double")) || ...
            size(variable, 2) ~= 1 || ~isreal(variable) || ...
            any(~isfinite(variable), "all")
        error( ...
            "v2xsim:positioning:MustBe2DPositionTable", ...
            "Position variable %s must be a finite, real, " + ...
            "single-column floating-point array.", ...
            variableName);
    end
end

rowNames = value.Properties.RowNames;
if height(value) > 0 && ...
        (isempty(rowNames) || numel(rowNames) ~= height(value))
    error( ...
        "v2xsim:positioning:MustBe2DPositionTable", ...
        "The position table must provide one unique row name per vehicle.");
end
end
