function simValues = applyPositionErrorChain( ...
        simParams,simValues,simulationTimeSeconds)
%APPLYPOSITIONERRORCHAIN Update controller-visible vehicle positions.
%   Scenario-managed vehicles are transformed as a named position table.
%   Legacy-managed stations such as RSUs retain their existing positions.

if ~isfield(simValues,'positionErrorChain') || ...
        isempty(simValues.positionErrorChain.Modules)
    return
end

scenarioVehicleIDs = simValues.scenarioVehicleIDs;
rowNames = simValues.scenarioVehicleRowNames;
apparentPositions = table( ...
    simValues.XvehicleEstimated(scenarioVehicleIDs), ...
    simValues.YvehicleEstimated(scenarioVehicleIDs), ...
    VariableNames=["X","Y"], ...
    RowNames=rowNames);
context = createContext( ...
    simValues.scenario,simulationTimeSeconds, ...
    simParams.positionTimeResolution,simParams.simulationTime);

[positionErrorChain,apparentPositions] = ...
    simValues.positionErrorChain.apply(apparentPositions,context);
simValues.positionErrorChain = positionErrorChain;
simValues.XvehicleEstimated(scenarioVehicleIDs) = apparentPositions.X;
simValues.YvehicleEstimated(scenarioVehicleIDs) = apparentPositions.Y;
end

function context = createContext( ...
        scenario,simulationTimeSeconds,timeStepSeconds,durationSeconds)
if isa( ...
        scenario, ...
        'v2xsim.vehicle.scenarios.ExitRampHighwayScenario')
    context = v2xsim.positioning.ExitRampPositionErrorContext( ...
        scenario,simulationTimeSeconds,timeStepSeconds,durationSeconds);
else
    actualPositions = ...
        scenario.VehicleKinematics(:,["X","Y"]);
    context = v2xsim.positioning.PositionErrorContext( ...
        actualPositions,simulationTimeSeconds, ...
        timeStepSeconds,durationSeconds);
end
end
