function simValues = applyPositionErrorChain( ...
        simParams,simValues,simulationTimeSeconds)
%APPLYPOSITIONERRORCHAIN Update controller-visible vehicle positions.
%   Position-error modules receive only named vehicle rows. Fixed RSU rows
%   remain unchanged in the complete UE estimate.

if ~isfield(simValues,'positionErrorChain') || ...
        isempty(simValues.positionErrorChain.Modules)
    return
end

world = simValues.world;
uePositions = table( ...
    simValues.XvehicleEstimated, ...
    simValues.YvehicleEstimated, ...
    VariableNames=["X","Y"], ...
    RowNames=cellstr(world.UeIds));
apparentVehiclePositions = uePositions( ...
    cellstr(world.VehicleIds),:);
context = createContext( ...
    world.TrafficScenario,simulationTimeSeconds, ...
    simParams.positionTimeResolution,simParams.simulationTime);

[positionErrorChain,apparentVehiclePositions] = ...
    simValues.positionErrorChain.apply( ...
        apparentVehiclePositions,context);
simValues.positionErrorChain = positionErrorChain;

apparentVehiclePositions = apparentVehiclePositions( ...
    cellstr(world.VehicleIds),:);
uePositions(cellstr(world.VehicleIds),:) = ...
    apparentVehiclePositions;
simValues.XvehicleEstimated = uePositions.X;
simValues.YvehicleEstimated = uePositions.Y;
end

function context = createContext( ...
        scenario,simulationTimeSeconds,timeStepSeconds,durationSeconds)
if isa( ...
        scenario, ...
        'v2xsim.vehicle.scenarios.ExitRampHighwayScenario')
    context = v2xsim.positioning.ExitRampPositionErrorContext( ...
        scenario,simulationTimeSeconds,timeStepSeconds,durationSeconds);
else
    actualPositions = ...
        scenario.VehicleKinematics(:,["X","Y"]);
    context = v2xsim.positioning.PositionErrorContext( ...
        actualPositions,simulationTimeSeconds, ...
        timeStepSeconds,durationSeconds);
end
end
