function [simParams,simValues,positionManagement,appParams] = ...
        initVehiclePositions(simParams,appParams)
%INITVEHICLEPOSITIONS Bridge Scenario initialization into legacy structs.

scenario = createScenario( ...
    simParams.typeOfScenario,simParams.scenarioOptions);
vehicleKinematics = scenario.VehicleKinematics;
vehicleCount = height(vehicleKinematics);

if vehicleCount==0
    error('v2xsim:legacy:NoVehicles', ...
        'The configured scenario contains no vehicles.');
end

world = v2xsim.World(scenario,createRsuPositions(appParams));
simValues.world = world;
simValues.IDvehicle = (1:numel(world.UeIds)).';
simValues.maxID = numel(world.UeIds);

positionManagement = v2xsim.legacy.projectWorldToPositionManagement( ...
    world,positionManagementForScenario(scenario));

if isfield(simParams,'positionErrorChain')
    simValues.positionErrorChain = simParams.positionErrorChain;
else
    simValues.positionErrorChain = ...
        v2xsim.positioning.PositionErrorChain();
end
simValues.XvehicleEstimatedLegacy = ...
    positionManagement.XvehicleReal;
simValues.YvehicleEstimatedLegacy = ...
    positionManagement.YvehicleReal;
simValues.XvehicleEstimated = ...
    simValues.XvehicleEstimatedLegacy;
simValues.YvehicleEstimated = ...
    simValues.YvehicleEstimatedLegacy;
simValues = applyPositionErrorChain(simParams,simValues,0);

% Legacy asynchronous-transmitter selection is independent of mobility.
if simParams.technology==constants.TECH_ONLY_CV2X && ...
        simParams.BRAlgorithm==constants.REASSIGN_BR_STD_MODE_4 && ...
    simParams.asynMode==1
    asynchronousVehicleCount = ...
        ceil(vehicleCount*simParams.percAsynUser);
    [hasVehicleId,vehicleUeIDs] = ...
        ismember(world.VehicleIds,world.UeIds);
    if ~all(hasVehicleId)
        error('v2xsim:legacy:InvalidWorldIdentity', ...
            'Every World.VehicleId must occur in World.UeIds.');
    end
    randomizedVehicleIDs = vehicleUeIDs(randperm(vehicleCount));
    randomizedVehicleIDs = randomizedVehicleIDs(:);
    simParams.IDvehicleAsyn = sort( ...
        randomizedVehicleIDs(1:asynchronousVehicleCount));
end
end

function rsuPositions = createRsuPositions(appParams)
if appParams.nRSUs==0
    rsuPositions = table( ...
        zeros(0,1),zeros(0,1), ...
        VariableNames=["X","Y"]);
    return
end

x = double(appParams.RSU_xLocation(:));
y = double(appParams.RSU_yLocation(:));
if numel(x)~=appParams.nRSUs || numel(y)~=appParams.nRSUs
    error('v2xsim:legacy:InvalidRsuPositionCount', ...
        ['nRSUs must equal the number of configured RSU X and Y ', ...
        'coordinates.']);
end

rsuIds = compose("RSU%d",(1:appParams.nRSUs).');
rsuPositions = table( ...
    x,y,VariableNames=["X","Y"],RowNames=cellstr(rsuIds));
end

function scenario = createScenario(typeOfScenario,scenarioOptions)
switch typeOfScenario
    case 'BrownianMotionScenario'
        scenario = ...
            v2xsim.vehicle.scenarios.BrownianMotionScenario( ...
                scenarioOptions.VehicleCount, ...
                SimulationAreaSize= ...
                    scenarioOptions.SimulationAreaSize, ...
                MeanVehicleSpeed= ...
                    scenarioOptions.MeanVehicleSpeed, ...
                VehicleSpeedStandardDeviation= ...
                    scenarioOptions.VehicleSpeedStandardDeviation);

    case 'BidirectionalHighwayScenario'
        scenario = ...
            v2xsim.vehicle.scenarios.BidirectionalHighwayScenario( ...
                scenarioOptions.VehicleCount, ...
                NLanes=scenarioOptions.NLanes, ...
                LaneWidth=scenarioOptions.LaneWidth, ...
                RoadLength=scenarioOptions.RoadLength, ...
                CentralDividerWidth= ...
                    scenarioOptions.CentralDividerWidth, ...
                MeanVehicleSpeed= ...
                    scenarioOptions.MeanVehicleSpeed, ...
                VehicleSpeedStandardDeviation= ...
                    scenarioOptions.VehicleSpeedStandardDeviation, ...
                RerollSpeedOnWrapAround= ...
                    scenarioOptions.RerollSpeedOnWrapAround);

    case 'EtsiHighwayScenario'
        scenario = v2xsim.vehicle.scenarios.EtsiHighwayScenario( ...
            scenarioOptions.TrafficModel, ...
            Placement=scenarioOptions.Placement, ...
            MinimumRoadLength=scenarioOptions.MinimumRoadLength);

    case 'ExitRampHighwayScenario'
        scenario = ...
            v2xsim.vehicle.scenarios.ExitRampHighwayScenario( ...
                scenarioOptions.VehicleCount, ...
                NLanes=scenarioOptions.NLanes, ...
                LaneWidth=scenarioOptions.LaneWidth, ...
                RoadLength=scenarioOptions.RoadLength, ...
                CentralDividerWidth= ...
                    scenarioOptions.CentralDividerWidth, ...
                MeanVehicleSpeed= ...
                    scenarioOptions.MeanVehicleSpeed, ...
                VehicleSpeedStandardDeviation= ...
                    scenarioOptions.VehicleSpeedStandardDeviation, ...
                RerollSpeedOnWrapAround= ...
                    scenarioOptions.RerollSpeedOnWrapAround, ...
                ExitProbability= ...
                    scenarioOptions.ExitProbability, ...
                MergeDistance=scenarioOptions.MergeDistance);

    otherwise
        error('v2xsim:legacy:UnknownScenario', ...
            'Unsupported Scenario class name: %s.',typeOfScenario);
end
end

function positionManagement = positionManagementForScenario(scenario)
positionManagement = struct();

if isa(scenario,'v2xsim.vehicle.scenarios.BrownianMotionScenario')
    positionManagement.Xmin = 0;
    positionManagement.Xmax = scenario.SimulationAreaSize;
    positionManagement.Ymin = 0;
    positionManagement.Ymax = scenario.SimulationAreaSize;
    return
end

if isa(scenario,'v2xsim.vehicle.scenario.highway.HighwayScenario')
    positionManagement.Xmin = 0;
    positionManagement.Xmax = scenario.RoadLength;
    yExtent = max(scenario.Geometry.getAbsoluteLaneCenters());
    if isa(scenario.Geometry, ...
            'v2xsim.vehicle.scenario.highway.ExitRampGeometry')
        yExtent = yExtent + scenario.RoadLength/2;
    end
    positionManagement.Ymin = -yExtent;
    positionManagement.Ymax = yExtent;
    return
end

error('v2xsim:legacy:UnsupportedScenarioGeometry', ...
    'No legacy bounds projection exists for class %s.',class(scenario));
end
