function [simParams,simValues,positionManagement,appParams] = ...
        initVehiclePositions(simParams,appParams)
%INITVEHICLEPOSITIONS Bridge Scenario initialization into legacy structs.

scenario = createScenario( ...
    simParams.typeOfScenario,simParams.scenarioOptions);
vehicleKinematics = scenario.VehicleKinematics;
vehicleCount = height(vehicleKinematics);

if vehicleCount==0
    error('v2xsim:legacy:NoVehicles', ...
        'The configured scenario contains no vehicles.');
end

% Keep the value object and the row-name-to-legacy-ID mapping together.
% The mapping remains authoritative if a Scenario later reorders its rows.
simValues.scenario = scenario;
simValues.scenarioVehicleRowNames = ...
    vehicleKinematics.Properties.RowNames;
simValues.scenarioVehicleIDs = (1:vehicleCount).';
simValues.IDvehicle = simValues.scenarioVehicleIDs;
simValues.maxID = vehicleCount;

positionManagement = projectKinematics( ...
    vehicleKinematics,positionManagementForScenario(scenario));

% RSUs remain legacy-managed fixed stations and are not inserted into the
% Scenario's fixed vehicle set.
if appParams.nRSUs>0
    idRSUs = simValues.maxID+1:simValues.maxID+appParams.nRSUs;
    simValues.maxID = simValues.maxID + appParams.nRSUs;
    simValues.IDvehicle = [simValues.IDvehicle; idRSUs.'];
    positionManagement.XvehicleReal = [ ...
        positionManagement.XvehicleReal; appParams.RSU_xLocation.'];
    positionManagement.YvehicleReal = [ ...
        positionManagement.YvehicleReal; appParams.RSU_yLocation.'];
    positionManagement.v = [ ...
        positionManagement.v; zeros(appParams.nRSUs,1)];
    positionManagement.direction = [ ...
        positionManagement.direction; zeros(appParams.nRSUs,1)];
end

% Compatibility aliases used by integrations outside this checkout. The
% WiLabV2Xsim sources themselves use XvehicleReal and YvehicleReal.
positionManagement.XVehicle = positionManagement.XvehicleReal;
positionManagement.YVehicle = positionManagement.YvehicleReal;

if isfield(simParams,'positionErrorChain')
    simValues.positionErrorChain = simParams.positionErrorChain;
else
    simValues.positionErrorChain = ...
        v2xsim.positioning.PositionErrorChain();
end
simValues.XvehicleEstimatedLegacy = ...
    positionManagement.XvehicleReal;
simValues.YvehicleEstimatedLegacy = ...
    positionManagement.YvehicleReal;
simValues.XvehicleEstimated = ...
    simValues.XvehicleEstimatedLegacy;
simValues.YvehicleEstimated = ...
    simValues.YvehicleEstimatedLegacy;
simValues = applyPositionErrorChain(simParams,simValues,0);

% Legacy asynchronous-transmitter selection is independent of mobility.
if simParams.technology==constants.TECH_ONLY_CV2X && ...
        simParams.BRAlgorithm==constants.REASSIGN_BR_STD_MODE_4 && ...
        simParams.asynMode==1
    asynchronousVehicleCount = ...
        ceil(vehicleCount*simParams.percAsynUser);
    randomizedVehicleIDs = simValues.scenarioVehicleIDs( ...
        randperm(vehicleCount));
    simParams.IDvehicleAsyn = sort( ...
        randomizedVehicleIDs(1:asynchronousVehicleCount));
end
end

function scenario = createScenario(typeOfScenario,scenarioOptions)
switch typeOfScenario
    case 'BrownianMotionScenario'
        scenario = ...
            v2xsim.vehicle.scenarios.BrownianMotionScenario( ...
                scenarioOptions.VehicleCount, ...
                SimulationAreaSize= ...
                    scenarioOptions.SimulationAreaSize, ...
                MeanVehicleSpeed= ...
                    scenarioOptions.MeanVehicleSpeed, ...
                VehicleSpeedStandardDeviation= ...
                    scenarioOptions.VehicleSpeedStandardDeviation);

    case 'BidirectionalHighwayScenario'
        scenario = ...
            v2xsim.vehicle.scenarios.BidirectionalHighwayScenario( ...
                scenarioOptions.VehicleCount, ...
                NLanes=scenarioOptions.NLanes, ...
                LaneWidth=scenarioOptions.LaneWidth, ...
                RoadLength=scenarioOptions.RoadLength, ...
                CentralDividerWidth= ...
                    scenarioOptions.CentralDividerWidth, ...
                MeanVehicleSpeed= ...
                    scenarioOptions.MeanVehicleSpeed, ...
                VehicleSpeedStandardDeviation= ...
                    scenarioOptions.VehicleSpeedStandardDeviation, ...
                RerollSpeedOnWrapAround= ...
                    scenarioOptions.RerollSpeedOnWrapAround);

    case 'EtsiHighwayScenario'
        scenario = v2xsim.vehicle.scenarios.EtsiHighwayScenario( ...
            scenarioOptions.TrafficModel, ...
            Placement=scenarioOptions.Placement, ...
            MinimumRoadLength=scenarioOptions.MinimumRoadLength);

    case 'ExitRampHighwayScenario'
        scenario = ...
            v2xsim.vehicle.scenarios.ExitRampHighwayScenario( ...
                scenarioOptions.VehicleCount, ...
                NLanes=scenarioOptions.NLanes, ...
                LaneWidth=scenarioOptions.LaneWidth, ...
                RoadLength=scenarioOptions.RoadLength, ...
                CentralDividerWidth= ...
                    scenarioOptions.CentralDividerWidth, ...
                MeanVehicleSpeed= ...
                    scenarioOptions.MeanVehicleSpeed, ...
                VehicleSpeedStandardDeviation= ...
                    scenarioOptions.VehicleSpeedStandardDeviation, ...
                RerollSpeedOnWrapAround= ...
                    scenarioOptions.RerollSpeedOnWrapAround, ...
                ExitProbability= ...
                    scenarioOptions.ExitProbability, ...
                MergeDistance=scenarioOptions.MergeDistance);

    otherwise
        error('v2xsim:legacy:UnknownScenario', ...
            'Unsupported Scenario class name: %s.',typeOfScenario);
end
end

function positionManagement = positionManagementForScenario(scenario)
positionManagement = struct();

if isa(scenario,'v2xsim.vehicle.scenarios.BrownianMotionScenario')
    positionManagement.Xmin = 0;
    positionManagement.Xmax = scenario.SimulationAreaSize;
    positionManagement.Ymin = 0;
    positionManagement.Ymax = scenario.SimulationAreaSize;
    return
end

if isa(scenario,'v2xsim.vehicle.scenario.highway.HighwayScenario')
    positionManagement.Xmin = 0;
    positionManagement.Xmax = scenario.RoadLength;
    yExtent = max(scenario.Geometry.getAbsoluteLaneCenters());
    if isa(scenario.Geometry, ...
            'v2xsim.vehicle.scenario.highway.ExitRampGeometry')
        yExtent = yExtent + scenario.RoadLength/2;
    end
    positionManagement.Ymin = -yExtent;
    positionManagement.Ymax = yExtent;
    return
end

error('v2xsim:legacy:UnsupportedScenarioGeometry', ...
    'No legacy bounds projection exists for class %s.',class(scenario));
end

function positionManagement = projectKinematics( ...
        vehicleKinematics,positionManagement)
positionManagement.XvehicleReal = vehicleKinematics.X;
positionManagement.YvehicleReal = vehicleKinematics.Y;

speed = hypot(vehicleKinematics.vX,vehicleKinematics.vY);
direction = complex(zeros(height(vehicleKinematics),1));
movingVehicles = speed>0;
direction(movingVehicles) = complex( ...
    vehicleKinematics.vX(movingVehicles)./speed(movingVehicles), ...
    vehicleKinematics.vY(movingVehicles)./speed(movingVehicles));

positionManagement.v = speed;
positionManagement.direction = direction;
end
